create extension if not exists postgis;

create table if not exists public.pole_datasets (
  id bigint generated by default as identity primary key,
  name text not null,
  source text,
  storage_path text,
  content_hash text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  created_by uuid references auth.users(id)
);

alter table public.pole_datasets enable row level security;

create policy "Pole datasets are viewable by admins"
  on public.pole_datasets for select
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_admin = true
    )
  );

create policy "Admins can insert pole datasets"
  on public.pole_datasets for insert
  with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_admin = true
    )
  );

create policy "Admins can update pole datasets"
  on public.pole_datasets for update
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_admin = true
    )
  );

create policy "Admins can delete pole datasets"
  on public.pole_datasets for delete
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_admin = true
    )
  );

create table if not exists public.poles (
  id bigint generated by default as identity primary key,
  dataset_id bigint not null references public.pole_datasets(id) on delete cascade,
  source_layer text,
  source_feature_id text,
  identifier text,
  plate text,
  address text,
  geom extensions.geography(point, 4326) not null,
  latitude double precision,
  longitude double precision,
  raw_properties jsonb default '{}'::jsonb,
  imported_at timestamptz default now(),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.poles enable row level security;

create policy "Poles are viewable by everyone"
  on public.poles for select
  using (true);

create policy "Admins can insert poles"
  on public.poles for insert
  with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_admin = true
    )
  );

create policy "Admins can update poles"
  on public.poles for update
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_admin = true
    )
  );

create policy "Admins can delete poles"
  on public.poles for delete
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_admin = true
    )
  );

create index if not exists poles_geom_gix on public.poles using gist (geom);
create index if not exists poles_dataset_id_idx on public.poles (dataset_id);
create index if not exists poles_identifier_idx on public.poles (identifier);
create index if not exists poles_plate_idx on public.poles (plate);

create trigger update_pole_datasets_updated_at
  before update on public.pole_datasets
  for each row
  execute function public.handle_updated_at();

create trigger update_poles_updated_at
  before update on public.poles
  for each row
  execute function public.handle_updated_at();

alter table if exists public.reports
  add column if not exists pole_id bigint references public.poles(id),
  add column if not exists reported_post_identifier text,
  add column if not exists reported_plate text,
  add column if not exists issue_type text,
  add column if not exists reported_pole_distance_m integer;

create index if not exists reports_pole_id_idx on public.reports (pole_id);

create or replace function public.nearest_poles(
  lat double precision,
  lng double precision,
  radius_m integer default 60,
  max_results integer default 5
)
returns table (
  pole_id bigint,
  identifier text,
  plate text,
  address text,
  latitude double precision,
  longitude double precision,
  distance_m integer
)
language sql
stable
as $$
  with params as (
    select
      extensions.st_setsrid(extensions.st_makepoint(lng, lat), 4326)::extensions.geography as user_geog,
      greatest(1, least(radius_m, 5000))::integer as radius_m_sanitized,
      greatest(1, least(max_results, 25))::integer as max_results_sanitized
  )
  select
    p.id as pole_id,
    p.identifier,
    p.plate,
    p.address,
    p.latitude,
    p.longitude,
    round(extensions.st_distance(p.geom, params.user_geog))::integer as distance_m
  from public.poles p
  cross join params
  where extensions.st_dwithin(p.geom, params.user_geog, params.radius_m_sanitized)
  order by extensions.st_distance(p.geom, params.user_geog) asc
  limit (select max_results_sanitized from params);
$$;

grant execute on function public.nearest_poles(double precision, double precision, integer, integer) to anon, authenticated;
