-- 206_trombone_agora.sql
--
-- Trombone Agora: acontecimentos da cidade, com previsao, prorrogacao,
-- resolucao e confirmacao da comunidade. Mais o acompanhamento de area que faz
-- Minha Rua saber quando algo esta acontecendo na regiao de quem le.
--
-- POR QUE ACONTECIMENTO, E NAO NOTIFICACAO
--
-- Um push e um disparo: existe no instante em que sai e some. "Falta d'agua no
-- Morada Nobre" nao e um instante — comeca, tem previsao, e prorrogada, volta,
-- e depois alguem precisa dizer se voltou mesmo. Modelado como notificacao, o
-- app so consegue responder "algo foi avisado"; modelado como linha com estado,
-- responde "o que esta acontecendo agora, desde quando e ate quando".
--
-- O push continua existindo — mas como CONSEQUENCIA da linha, nao como o dado.
-- Cada acontecimento novo, prorrogacao e resolucao insere em `notifications`, e
-- o webhook que ja existe leva ao aparelho. Nenhuma Edge Function nova: o campo
-- `link` da notificacao (`/agora/438`) ja e o que send-push-notification usa
-- para montar o destino do toque (ver `computeTargetUrl` la).
--
-- POR QUE `city_id` E NAO `tenant_id`
--
-- O plano fala em tenant. Neste projeto o inquilino E a cidade desde a
-- nacionalizacao (migracoes 144, 151, 154, 158): `cities` e a raiz de escopo,
-- `ambassador_cities` diz quem manda em qual, e `is_ambassador_of` ja responde
-- a pergunta. Um `tenant_id` paralelo seria uma segunda autoridade de escopo,
-- divergindo em silencio da primeira.
--
-- AS POLICIES ESTAO AQUI, DE PROPOSITO
--
-- As migracoes 202, 203 e 204 registram o problema: neste projeto as policies
-- moram no painel do Supabase e nao no git, entao toda tabela nova vira regra
-- invisivel ao codigo. Elas evitaram criar tabela por isso. Aqui nao da para
-- evitar — um acontecimento nao cabe numa coluna — entao vale a outra metade da
-- mesma preocupacao: TODA policy destas seis tabelas esta escrita neste
-- arquivo, versionada e revisavel em diff.

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 1 — TABELAS
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1.1 O acontecimento ─────────────────────────────────────────────────────
--
-- ESTADOS, E O QUE `EXTENDED` E `REOPENED` REALMENTE SAO
--
-- O plano desenha ACTIVE -> EXTENDED -> ACTIVE e RESOLVED -> REOPENED ->
-- ACTIVE. Os dois voltam para ACTIVE no passo seguinte, ou seja: nao sao
-- estados de repouso, sao ACONTECIMENTOS na linha do tempo. Guardados como
-- status, seriam valores em que nenhuma consulta jamais encontra linha, e toda
-- tela precisaria tratar 'extended' como sinonimo de 'active'.
--
-- Eles entram como `type` em city_event_updates, que e onde a historia mora.
--
-- `awaiting_confirmation` E estado de repouso, e responde a regra 4 do plano
-- ("a previsao vencida nao encerra automaticamente"): a previsao passou, o
-- responsavel foi avisado, e ninguem ainda disse se normalizou. Sem ele, um
-- evento vencido fica indistinguivel de um em dia — e a cidade le
-- "previsao: hoje ate 18h" as 22h.

create table if not exists public.city_events (
  id                  bigint generated by default as identity primary key,
  city_id             bigint not null references public.cities(id) on delete cascade,

  type                text not null,
  title               text not null,
  description         text,

  severity            text not null default 'warning',
  status              text not null default 'active',

  started_at          timestamptz not null default now(),
  estimated_end_at    timestamptz,
  resolved_at         timestamptz,

  source_name         text,
  source_url          text,

  created_by          uuid references public.profiles(id) on delete set null,
  created_by_role     text,

  resolved_by         uuid references public.profiles(id) on delete set null,
  resolved_by_role    text,

  -- Quantas vezes o evento ja foi dado como resolvido. E o "ciclo" da regra do
  -- plano: uma confirmacao ativa por pessoa POR CICLO. Reabrir soma 1 e a
  -- enquete recomeca do zero, sem apagar as respostas do ciclo anterior — que
  -- sao justamente a prova de que a reabertura fazia sentido.
  confirmation_cycle  integer not null default 0,

  -- Quando o responsavel foi avisado de que a previsao venceu. Existe para a
  -- varredura ser idempotente: rodar de novo nao reavisa ninguem.
  overdue_notified_at timestamptz,

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  constraint city_events_type_valido check (type in (
    'water_outage', 'power_outage', 'road_block', 'traffic', 'weather',
    'public_transport', 'health', 'construction', 'event', 'public_notice', 'other'
  )),
  constraint city_events_severity_valida check (severity in ('info', 'warning', 'critical')),
  constraint city_events_status_valido check (status in (
    'draft', 'scheduled', 'active', 'awaiting_confirmation', 'resolved', 'cancelled'
  )),
  -- Regra 9 do plano: toda resolucao tem autor e data.
  constraint city_events_resolvido_tem_desfecho check (
    status <> 'resolved' or (resolved_at is not null and resolved_by is not null)
  ),
  constraint city_events_titulo_nao_vazio check (length(btrim(title)) > 0)
);

comment on table public.city_events is
  'Acontecimentos da cidade (Trombone Agora). Um por regiao, nunca uma copia por rua.';
comment on column public.city_events.confirmation_cycle is
  'Numero de resolucoes ja anunciadas. Reabrir incrementa; a enquete da comunidade e por ciclo.';
comment on column public.city_events.overdue_notified_at is
  'Quando o responsavel foi avisado de previsao vencida. Torna a varredura idempotente.';

create index if not exists city_events_cidade_status_idx
  on public.city_events (city_id, status, started_at desc);

create index if not exists city_events_previsao_vencida_idx
  on public.city_events (estimated_end_at)
  where status = 'active' and estimated_end_at is not null;

create index if not exists city_events_resolvidos_idx
  on public.city_events (city_id, resolved_at desc)
  where status = 'resolved';

-- ── 1.2 Regioes atingidas ───────────────────────────────────────────────────
--
-- Regra 3 do plano: um acontecimento regional NAO e duplicado por rua. A rua
-- descobre que esta atingida por consulta — bairro dela dentro das areas, ou
-- evento de cidade inteira — e nao por uma copia da linha.
--
-- POR QUE SO city / neighborhood / street
--
-- O plano lista tambem `district` e `polygon`. Nenhum dos dois tem tabela neste
-- banco. Aceita-los no CHECK criaria area que nada resolve: o evento existiria,
-- ninguem seria encontrado, e o silencio pareceria "ninguem acompanha a
-- regiao". Entram quando houver o que apontar.
--
-- `area_id` e uuid porque `bairros.id` e `pavement_streets.id` sao uuid. A
-- cidade nao precisa de id proprio aqui: ela ja esta em city_events.city_id, e
-- guardar de novo abriria a chance de os dois divergirem.

create table if not exists public.city_event_areas (
  id            bigint generated by default as identity primary key,
  city_event_id bigint not null references public.city_events(id) on delete cascade,
  area_type     text not null,
  area_id       uuid,
  created_at    timestamptz not null default now(),

  constraint city_event_areas_tipo_valido check (area_type in ('city', 'neighborhood', 'street')),
  constraint city_event_areas_id_conforme_tipo check (
    (area_type = 'city' and area_id is null)
    or (area_type <> 'city' and area_id is not null)
  )
);

comment on table public.city_event_areas is
  'Onde o acontecimento pega. area_type=city vale a cidade inteira do evento e deixa area_id nulo.';

create unique index if not exists city_event_areas_sem_repeticao
  on public.city_event_areas
     (city_event_id, area_type, coalesce(area_id, '00000000-0000-0000-0000-000000000000'::uuid));

create index if not exists city_event_areas_por_area_idx
  on public.city_event_areas (area_type, area_id);

-- ── 1.3 Linha do tempo ──────────────────────────────────────────────────────
--
-- Regra 10: o historico nunca e apagado quando o status muda. Toda transicao
-- escreve uma linha aqui, e nenhuma tela reconstroi a historia a partir do
-- estado atual — porque o estado atual nao sabe que a previsao ja foi 18h.
--
-- A tabela e append-only por RLS: existe policy de insert, nao existe de update
-- nem de delete. Nao e descuido; e a regra 10 escrita como permissao.

create table if not exists public.city_event_updates (
  id                   bigint generated by default as identity primary key,
  city_event_id        bigint not null references public.city_events(id) on delete cascade,

  type                 text not null,
  message              text,

  old_estimated_end_at timestamptz,
  new_estimated_end_at timestamptz,

  created_by           uuid references public.profiles(id) on delete set null,
  created_by_role      text,

  created_at           timestamptz not null default now(),

  constraint city_event_updates_tipo_valido check (type in (
    'created', 'progress', 'extended', 'resolved', 'reopened', 'cancelled', 'community_divergence'
  ))
);

comment on table public.city_event_updates is
  'Historia do acontecimento. Append-only: ha policy de insert, nao ha de update nem delete.';

create index if not exists city_event_updates_linha_do_tempo_idx
  on public.city_event_updates (city_event_id, created_at desc);

-- ── 1.4 Confirmacao da comunidade ───────────────────────────────────────────

create table if not exists public.city_event_confirmations (
  id            bigint generated by default as identity primary key,
  city_event_id bigint not null references public.city_events(id) on delete cascade,
  user_id       uuid not null references public.profiles(id) on delete cascade,
  cycle         integer not null default 0,
  status        text not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint city_event_confirmations_status_valido check (status in ('resolved', 'not_resolved'))
);

comment on table public.city_event_confirmations is
  'Resposta do morador a "ja voltou?". Uma por pessoa por ciclo de resolucao.';

create unique index if not exists city_event_confirmations_uma_por_ciclo
  on public.city_event_confirmations (city_event_id, user_id, cycle);

-- ── 1.5 Acompanhamento de area ──────────────────────────────────────────────
--
-- POR QUE UMA PREFERENCIA A MAIS QUE O PLANO PEDE
--
-- O plano lista seis chaves (agua, energia, transito, obras, eventos,
-- comunicados) e onze tipos. Sobram `weather`, `health` e `other`. Encaixa-los
-- em `events_alerts` faria "alerta de chuva forte" ser desligado por quem so
-- nao queria saber de feira livre — que e o unico dos tres que da para perder
-- sem consequencia.
--
-- `critical_alerts` cobre os tres e vem ligado. Continua desligavel: ninguem e
-- obrigado a nada. Mas exige um gesto proprio.

create table if not exists public.user_area_follows (
  id                   bigint generated by default as identity primary key,
  user_id              uuid not null references public.profiles(id) on delete cascade,

  area_type            text not null,
  area_id              uuid,
  city_id              bigint references public.cities(id) on delete cascade,

  water_alerts         boolean not null default true,
  power_alerts         boolean not null default true,
  traffic_alerts       boolean not null default true,
  works_alerts         boolean not null default true,
  events_alerts        boolean not null default true,
  public_notice_alerts boolean not null default true,
  critical_alerts      boolean not null default true,

  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),

  constraint user_area_follows_tipo_valido check (area_type in ('city', 'neighborhood', 'street')),
  constraint user_area_follows_id_conforme_tipo check (
    (area_type = 'city' and area_id is null and city_id is not null)
    or (area_type <> 'city' and area_id is not null)
  )
);

comment on table public.user_area_follows is
  'Quem acompanha qual rua, bairro ou cidade, e com quais alertas ligados.';

create unique index if not exists user_area_follows_uma_por_cidade
  on public.user_area_follows (user_id, city_id) where area_type = 'city';

create unique index if not exists user_area_follows_uma_por_area
  on public.user_area_follows (user_id, area_type, area_id) where area_type <> 'city';

create index if not exists user_area_follows_por_area_idx
  on public.user_area_follows (area_type, area_id);

-- ── 1.6 Escopo do embaixador por bairro ─────────────────────────────────────
--
-- POR QUE ESTA TABELA NAO SUBSTITUI `ambassador_cities`
--
-- O plano (secao 24) sugere `ambassador_areas` como O escopo do embaixador.
-- Hoje quem responde isso e `ambassador_cities` + `is_ambassador_of`, usada em
-- pavimentacao, servicos, obras e moderacao. Trocar a autoridade quebraria as
-- quatro; manter as duas como autoridades iguais faria elas divergirem.
--
-- Entao esta tabela nao decide nada sozinha: ela apenas ESTREITA. Sem nenhuma
-- linha, o embaixador continua com a cidade inteira, exatamente como hoje. Com
-- linhas, so publica nos bairros listados. E aditiva por construcao — o
-- embaixador que ninguem configurou nao muda de comportamento.

create table if not exists public.ambassador_areas (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references public.profiles(id) on delete cascade,
  city_id    bigint not null references public.cities(id) on delete cascade,
  area_type  text not null default 'neighborhood',
  area_id    uuid not null,
  created_at timestamptz not null default now(),

  constraint ambassador_areas_tipo_valido check (area_type in ('neighborhood'))
);

comment on table public.ambassador_areas is
  'Estreita o escopo de um embaixador a bairros. Sem linhas, vale a cidade inteira de ambassador_cities.';

create unique index if not exists ambassador_areas_sem_repeticao
  on public.ambassador_areas (user_id, area_type, area_id);

-- ── 1.7 A notificacao aponta para o acontecimento ───────────────────────────
--
-- `notifications` ja tem `report_id` e `work_id` pelo mesmo motivo: sem a
-- coluna, apagar o evento deixaria a notificacao apontando para um /agora/438
-- inexistente. Com ela, o cascade limpa junto.

alter table public.notifications
  add column if not exists city_event_id bigint references public.city_events(id) on delete cascade;

create index if not exists notifications_city_event_idx
  on public.notifications (city_event_id) where city_event_id is not null;

-- ── 1.8 updated_at ──────────────────────────────────────────────────────────

drop trigger if exists city_events_updated_at on public.city_events;
create trigger city_events_updated_at
  before update on public.city_events
  for each row execute function public.handle_updated_at();

drop trigger if exists city_event_confirmations_updated_at on public.city_event_confirmations;
create trigger city_event_confirmations_updated_at
  before update on public.city_event_confirmations
  for each row execute function public.handle_updated_at();

drop trigger if exists user_area_follows_updated_at on public.user_area_follows;
create trigger user_area_follows_updated_at
  before update on public.user_area_follows
  for each row execute function public.handle_updated_at();

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 2 — QUEM PODE O QUE
-- ═══════════════════════════════════════════════════════════════════════════

-- O papel com que a pessoa age, para gravar em created_by_role/resolved_by_role.
--
-- Nao e enfeite de auditoria: a secao 12 do plano manda notificar "o
-- administrador, o embaixador responsavel, ou ambos, conforme a regra". Sem
-- saber com que papel a linha foi criada, essa escolha nao tem como existir
-- depois.
create or replace function public.city_event_role(p_user uuid, p_city_id bigint)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select case
    when p_user is null then null
    when public.is_master(p_user) then 'master'
    when public.is_admin(p_user) then 'admin'
    when public.is_ambassador_of(p_user, p_city_id) then 'ambassador'
    else null
  end;
$$;

-- Pode gerir acontecimentos desta cidade?
create or replace function public.can_manage_city_events(p_user uuid, p_city_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.city_event_role(p_user, p_city_id) is not null;
$$;

-- As areas pedidas cabem no escopo de quem esta publicando?
--
-- Admin e master passam direto. Embaixador SEM linhas em ambassador_areas
-- tambem — e a cidade inteira dele, como sempre foi. Embaixador COM bairros
-- designados so passa se cada area pedida estiver dentro deles.
create or replace function public.city_event_scope_ok(p_user uuid, p_city_id bigint, p_areas jsonb)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_designados integer;
  v_area       jsonb;
  v_tipo       text;
  v_id         uuid;
begin
  if p_user is null then return false; end if;
  if public.is_admin(p_user) or public.is_master(p_user) then return true; end if;
  if not public.is_ambassador_of(p_user, p_city_id) then return false; end if;

  select count(*) into v_designados
  from public.ambassador_areas
  where user_id = p_user and city_id = p_city_id;

  if v_designados = 0 then return true; end if;

  -- O apelido da coluna e explicito (`as t(item)`) porque `select value from
  -- jsonb_array_elements(...)` depende do nome do parametro OUT da funcao, e
  -- `... x` sozinho depende de como o Postgres resolve apelido de tabela sobre
  -- funcao escalar. Nomear a coluna tira as duas duvidas.
  for v_area in select t.item from jsonb_array_elements(coalesce(p_areas, '[]'::jsonb)) as t(item)
  loop
    v_tipo := v_area->>'area_type';

    -- Quem tem bairro designado nao publica para a cidade inteira: seria
    -- exatamente o escopo que a designacao existe para tirar.
    if v_tipo = 'city' then return false; end if;

    v_id := nullif(v_area->>'area_id', '')::uuid;
    if v_id is null then return false; end if;

    if v_tipo = 'neighborhood' then
      if not exists (
        select 1 from public.ambassador_areas aa
        where aa.user_id = p_user and aa.city_id = p_city_id
          and aa.area_type = 'neighborhood' and aa.area_id = v_id
      ) then
        return false;
      end if;

    elsif v_tipo = 'street' then
      -- Uma rua so cabe no escopo se o bairro dela couber. Rua sem bairro
      -- cadastrado nao cabe em nenhum: nao da para provar que cabe.
      if not exists (
        select 1
        from public.pavement_streets s
        join public.ambassador_areas aa
          on aa.area_type = 'neighborhood' and aa.area_id = s.bairro_id
        where s.id = v_id
          and aa.user_id = p_user and aa.city_id = p_city_id
      ) then
        return false;
      end if;

    else
      return false;
    end if;
  end loop;

  return true;
end;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 3 — QUEM E AVISADO
-- ═══════════════════════════════════════════════════════════════════════════

-- A audiencia de um acontecimento.
--
-- A REGRA DE ALCANCE, EM UMA FRASE: quem acompanha uma area que o evento toca,
-- COM a chave daquele tipo ligada.
--
-- "Toca" e o que a secao 11 do plano descreve e o que evita a copia por rua:
--
--   * segue a CIDADE  -> so quando o evento e de cidade inteira;
--   * segue um BAIRRO -> quando o bairro esta nas areas, quando uma rua listada
--                        fica nele, ou quando o evento e de cidade inteira;
--   * segue uma RUA   -> quando a rua esta listada, quando o bairro dela esta,
--                        ou quando o evento e de cidade inteira.
--
-- O caminho "rua -> bairro" e o que faz "falta d'agua no Morada Nobre" chegar a
-- quem acompanha so a propria rua, sem nenhuma linha por rua ter sido criada.
create or replace function public.city_event_audience(p_event_id bigint)
returns table (user_id uuid)
language sql
stable
security definer
set search_path = public
as $$
  with evento as (
    select e.id, e.city_id, e.type from public.city_events e where e.id = p_event_id
  ),
  areas as (
    select a.area_type, a.area_id from public.city_event_areas a where a.city_event_id = p_event_id
  ),
  cidade_inteira as (
    select exists (select 1 from areas where area_type = 'city') as sim
  ),
  bairros_atingidos as (
    select area_id as bairro_id from areas where area_type = 'neighborhood'
    union
    select s.bairro_id
      from public.pavement_streets s
      join areas a on a.area_type = 'street' and a.area_id = s.id
     where s.bairro_id is not null
  )
  select distinct f.user_id
  from public.user_area_follows f
  cross join evento e
  cross join cidade_inteira ci
  where
    -- A chave daquele tipo esta ligada para esta area?
    case e.type
      when 'water_outage'     then f.water_alerts
      when 'power_outage'     then f.power_alerts
      when 'road_block'       then f.traffic_alerts
      when 'traffic'          then f.traffic_alerts
      when 'public_transport' then f.traffic_alerts
      when 'construction'     then f.works_alerts
      when 'event'            then f.events_alerts
      when 'public_notice'    then f.public_notice_alerts
      else f.critical_alerts
    end
    and (
      (f.area_type = 'city' and f.city_id = e.city_id and ci.sim)

      or (f.area_type = 'neighborhood' and (
            f.area_id in (select bairro_id from bairros_atingidos)
            or (ci.sim and exists (
                 select 1 from public.bairros b where b.id = f.area_id and b.city_id = e.city_id
               ))
         ))

      or (f.area_type = 'street' and (
            f.area_id in (select area_id from areas where area_type = 'street')
            or exists (
                 select 1 from public.pavement_streets s
                 where s.id = f.area_id
                   and (
                     s.bairro_id in (select bairro_id from bairros_atingidos)
                     or (ci.sim and s.city_id = e.city_id)
                   )
               )
         ))
    );
$$;

-- Quem responde pela cidade: admin, master e embaixador ativo.
--
-- Quando o embaixador tem bairros designados, so entra se algum dos bairros
-- dele estiver no evento — senao todo embaixador da cidade seria acordado por
-- toda previsao vencida em qualquer bairro, que e o ruido que a designacao
-- existe para cortar.
create or replace function public.city_event_managers(p_event_id bigint)
returns table (user_id uuid)
language sql
stable
security definer
set search_path = public
as $$
  with evento as (
    select e.id, e.city_id from public.city_events e where e.id = p_event_id
  ),
  areas as (
    select a.area_type, a.area_id from public.city_event_areas a where a.city_event_id = p_event_id
  ),
  cidade_inteira as (
    select exists (select 1 from areas where area_type = 'city') as sim
  ),
  bairros_atingidos as (
    select area_id as bairro_id from areas where area_type = 'neighborhood'
    union
    select s.bairro_id
      from public.pavement_streets s
      join areas a on a.area_type = 'street' and a.area_id = s.id
     where s.bairro_id is not null
  )
  select distinct p.id
  from public.profiles p
  cross join evento e
  cross join cidade_inteira ci
  where p.is_admin = true
     or p.is_master = true
     or (
       exists (
         select 1 from public.ambassador_cities ac
         where ac.user_id = p.id and ac.city_id = e.city_id and ac.status = 'active'
       )
       and (
         not exists (
           select 1 from public.ambassador_areas aa
           where aa.user_id = p.id and aa.city_id = e.city_id
         )
         or ci.sim
         or exists (
           select 1 from public.ambassador_areas aa
           where aa.user_id = p.id and aa.city_id = e.city_id
             and aa.area_id in (select bairro_id from bairros_atingidos)
         )
       )
     );
$$;

-- Insere uma notificacao por pessoa da audiencia. Devolve quantas.
--
-- `p_skip` tira quem disparou a acao: o embaixador que publicou nao precisa ser
-- avisado do que acabou de escrever.
create or replace function public.notify_city_event_audience(
  p_event_id bigint,
  p_type     text,
  p_title    text,
  p_message  text,
  p_skip     uuid default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inseridas integer;
begin
  insert into public.notifications (user_id, type, title, message, link, city_event_id, is_read, created_at)
  select a.user_id, p_type, p_title, p_message, '/agora/' || p_event_id, p_event_id, false, now()
  from public.city_event_audience(p_event_id) a
  where p_skip is null or a.user_id <> p_skip;

  get diagnostics v_inseridas = row_count;
  return v_inseridas;
end;
$$;

create or replace function public.notify_city_event_managers(
  p_event_id bigint,
  p_type     text,
  p_title    text,
  p_message  text,
  p_link     text default null,
  p_skip     uuid default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inseridas integer;
begin
  insert into public.notifications (user_id, type, title, message, link, city_event_id, is_read, created_at)
  select m.user_id, p_type, p_title, p_message,
         coalesce(p_link, '/agora/' || p_event_id), p_event_id, false, now()
  from public.city_event_managers(p_event_id) m
  where p_skip is null or m.user_id <> p_skip;

  get diagnostics v_inseridas = row_count;
  return v_inseridas;
end;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 4 — ESCRITA (as RPCs)
-- ═══════════════════════════════════════════════════════════════════════════
--
-- POR QUE A TELA NAO GRAVA DIRETO
--
-- Existem policies de escrita para gestor (parte 6), e elas sao a autoridade.
-- Mas todo caminho do app passa por estas funcoes, porque cada transicao tem um
-- efeito colateral que a regra 8 e a 10 do plano exigem: escrever a linha do
-- tempo e avisar quem acompanha. Um UPDATE direto em `status` produziria um
-- evento resolvido sem nenhum registro de quem resolveu e sem ninguem saber.

-- Grava as areas de um evento a partir do jsonb [{area_type, area_id}].
-- A CIDADE DA AREA TEM QUE SER A CIDADE DO EVENTO
--
-- Sem esta checagem, um bairro de OUTRA cidade entrava na lista de areas e
-- `city_event_audience` — que casa o seguidor pelo id do bairro, nao pela
-- cidade — mandava "falta d'agua no Morada Nobre" para quem acompanha um
-- bairro homonimo a 600 km.
--
-- `city_event_scope_ok` nao pegava isso: ela devolve `true` na hora para admin
-- e master, e tambem para o embaixador que nao tem bairro designado — que e a
-- configuracao da maioria. Sobrava so o seletor da tela filtrando por cidade,
-- e tela nao e autoridade: a RPC esta aberta a `authenticated`.
--
-- Area inexistente cai no mesmo erro de proposito. `coalesce(b.city_id,
-- s.city_id)` vem nulo quando o uuid nao existe, e `is distinct from` trata
-- nulo como diferente — um id inventado nunca vira area silenciosa.
create or replace function public.set_city_event_areas(p_event_id bigint, p_areas jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_city_id bigint;
  v_fora    integer;
begin
  select city_id into v_city_id from public.city_events where id = p_event_id;
  if v_city_id is null then
    raise exception 'Acontecimento nao encontrado.' using errcode = 'P0002';
  end if;

  select count(*) into v_fora
  from jsonb_array_elements(coalesce(p_areas, '[]'::jsonb)) as t(item)
  left join public.bairros b
    on t.item->>'area_type' = 'neighborhood'
   and b.id = nullif(t.item->>'area_id', '')::uuid
  left join public.pavement_streets s
    on t.item->>'area_type' = 'street'
   and s.id = nullif(t.item->>'area_id', '')::uuid
  where t.item->>'area_type' <> 'city'
    and coalesce(b.city_id, s.city_id) is distinct from v_city_id;

  if v_fora > 0 then
    raise exception 'Ha % area(s) de outra cidade ou inexistente(s) na lista.', v_fora
      using errcode = '42501';
  end if;

  delete from public.city_event_areas where city_event_id = p_event_id;

  insert into public.city_event_areas (city_event_id, area_type, area_id)
  select
    p_event_id,
    t.item->>'area_type',
    case when t.item->>'area_type' = 'city' then null
         else nullif(t.item->>'area_id', '')::uuid end
  from jsonb_array_elements(coalesce(p_areas, '[]'::jsonb)) as t(item)
  on conflict do nothing;
end;
$$;

create or replace function public.create_city_event(
  p_city_id          bigint,
  p_type             text,
  p_title            text,
  p_areas            jsonb,
  p_description      text default null,
  p_severity         text default 'warning',
  p_started_at       timestamptz default null,
  p_estimated_end_at timestamptz default null,
  p_source_name      text default null,
  p_source_url       text default null,
  p_notify           boolean default true,
  p_status           text default 'active'
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user    uuid := auth.uid();
  v_role    text;
  v_id      bigint;
  v_inicio  timestamptz := coalesce(p_started_at, now());
  v_status  text := coalesce(p_status, 'active');
begin
  v_role := public.city_event_role(v_user, p_city_id);
  if v_role is null then
    raise exception 'Sem permissao para criar acontecimentos nesta cidade.' using errcode = '42501';
  end if;

  if jsonb_array_length(coalesce(p_areas, '[]'::jsonb)) = 0 then
    raise exception 'Escolha ao menos uma area atingida.' using errcode = '22023';
  end if;

  if not public.city_event_scope_ok(v_user, p_city_id, p_areas) then
    raise exception 'Alguma das areas escolhidas esta fora do seu escopo.' using errcode = '42501';
  end if;

  -- Um evento com inicio no futuro e `scheduled`, nao `active`: dizer "em
  -- andamento" as 10h sobre algo que comeca as 14h e informacao errada, e o
  -- push sairia com previsao que ainda nao vale.
  if v_status = 'active' and v_inicio > now() then
    v_status := 'scheduled';
  end if;

  if p_estimated_end_at is not null and p_estimated_end_at <= v_inicio then
    raise exception 'A previsao precisa ser depois do inicio.' using errcode = '22023';
  end if;

  insert into public.city_events (
    city_id, type, title, description, severity, status,
    started_at, estimated_end_at, source_name, source_url,
    created_by, created_by_role
  ) values (
    p_city_id, p_type, btrim(p_title), nullif(btrim(coalesce(p_description, '')), ''),
    coalesce(p_severity, 'warning'), v_status,
    v_inicio, p_estimated_end_at,
    nullif(btrim(coalesce(p_source_name, '')), ''), nullif(btrim(coalesce(p_source_url, '')), ''),
    v_user, v_role
  )
  returning id into v_id;

  perform public.set_city_event_areas(v_id, p_areas);

  insert into public.city_event_updates (city_event_id, type, message, new_estimated_end_at, created_by, created_by_role)
  values (v_id, 'created', nullif(btrim(coalesce(p_description, '')), ''), p_estimated_end_at, v_user, v_role);

  -- Rascunho nao avisa ninguem: e o unico estado em que o texto ainda pode
  -- estar errado de proposito.
  if p_notify and v_status = 'active' then
    perform public.notify_city_event_audience(
      v_id, 'city_event', btrim(p_title),
      coalesce(nullif(btrim(coalesce(p_description, '')), ''), 'Toque para ver a situacao.'),
      v_user
    );
  end if;

  return v_id;
end;
$$;

create or replace function public.update_city_event(
  p_event_id         bigint,
  p_title            text default null,
  p_description      text default null,
  p_type             text default null,
  p_severity         text default null,
  p_started_at       timestamptz default null,
  p_estimated_end_at timestamptz default null,
  p_source_name      text default null,
  p_source_url       text default null,
  p_areas            jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user  uuid := auth.uid();
  v_event public.city_events;
begin
  select * into v_event from public.city_events where id = p_event_id;
  if not found then
    raise exception 'Acontecimento nao encontrado.' using errcode = 'P0002';
  end if;

  if not public.can_manage_city_events(v_user, v_event.city_id) then
    raise exception 'Sem permissao para editar este acontecimento.' using errcode = '42501';
  end if;

  if p_areas is not null then
    if not public.city_event_scope_ok(v_user, v_event.city_id, p_areas) then
      raise exception 'Alguma das areas escolhidas esta fora do seu escopo.' using errcode = '42501';
    end if;
    perform public.set_city_event_areas(p_event_id, p_areas);
  end if;

  update public.city_events set
    title            = coalesce(nullif(btrim(coalesce(p_title, '')), ''), title),
    description      = coalesce(p_description, description),
    type             = coalesce(p_type, type),
    severity         = coalesce(p_severity, severity),
    started_at       = coalesce(p_started_at, started_at),
    estimated_end_at = coalesce(p_estimated_end_at, estimated_end_at),
    source_name      = coalesce(p_source_name, source_name),
    source_url       = coalesce(p_source_url, source_url)
  where id = p_event_id;
end;
$$;

-- Publica um rascunho. Separado do create porque publicar E o momento do push:
-- juntar as duas coisas faria salvar um rascunho disparar notificacao.
create or replace function public.publish_city_event(p_event_id bigint, p_notify boolean default true)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user  uuid := auth.uid();
  v_event public.city_events;
begin
  select * into v_event from public.city_events where id = p_event_id;
  if not found then
    raise exception 'Acontecimento nao encontrado.' using errcode = 'P0002';
  end if;
  if not public.can_manage_city_events(v_user, v_event.city_id) then
    raise exception 'Sem permissao.' using errcode = '42501';
  end if;
  if v_event.status not in ('draft', 'scheduled') then
    raise exception 'Este acontecimento ja foi publicado.' using errcode = '22023';
  end if;

  update public.city_events set status = 'active' where id = p_event_id;

  if p_notify then
    perform public.notify_city_event_audience(
      p_event_id, 'city_event', v_event.title,
      coalesce(v_event.description, 'Toque para ver a situacao.'), v_user
    );
  end if;
end;
$$;

-- Uma atualizacao de andamento, sem mexer em previsao nem status.
create or replace function public.add_city_event_progress(
  p_event_id bigint,
  p_message  text,
  p_notify   boolean default false
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user  uuid := auth.uid();
  v_event public.city_events;
  v_role  text;
  v_id    bigint;
begin
  select * into v_event from public.city_events where id = p_event_id;
  if not found then
    raise exception 'Acontecimento nao encontrado.' using errcode = 'P0002';
  end if;

  v_role := public.city_event_role(v_user, v_event.city_id);
  if v_role is null then
    raise exception 'Sem permissao.' using errcode = '42501';
  end if;
  if nullif(btrim(coalesce(p_message, '')), '') is null then
    raise exception 'Escreva a atualizacao.' using errcode = '22023';
  end if;

  insert into public.city_event_updates (city_event_id, type, message, created_by, created_by_role)
  values (p_event_id, 'progress', btrim(p_message), v_user, v_role)
  returning id into v_id;

  -- O push de andamento e OPCIONAL, e o padrao e nao mandar. "Equipe segue
  -- trabalhando" tres vezes num dia e o tipo de aviso que faz a pessoa desligar
  -- a notificacao e nunca mais receber a que importava.
  if p_notify then
    perform public.notify_city_event_audience(
      p_event_id, 'city_event_update', v_event.title, btrim(p_message), v_user
    );
  end if;

  return v_id;
end;
$$;

-- Prorroga. Secao 13 do plano.
create or replace function public.extend_city_event(
  p_event_id            bigint,
  p_new_estimated_end_at timestamptz,
  p_message             text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user  uuid := auth.uid();
  v_event public.city_events;
  v_role  text;
begin
  select * into v_event from public.city_events where id = p_event_id;
  if not found then
    raise exception 'Acontecimento nao encontrado.' using errcode = 'P0002';
  end if;

  v_role := public.city_event_role(v_user, v_event.city_id);
  if v_role is null then
    raise exception 'Sem permissao.' using errcode = '42501';
  end if;
  if p_new_estimated_end_at is null then
    raise exception 'Informe a nova previsao.' using errcode = '22023';
  end if;

  insert into public.city_event_updates (
    city_event_id, type, message, old_estimated_end_at, new_estimated_end_at, created_by, created_by_role
  ) values (
    p_event_id, 'extended', nullif(btrim(coalesce(p_message, '')), ''),
    v_event.estimated_end_at, p_new_estimated_end_at, v_user, v_role
  );

  -- Volta para `active` e ZERA o aviso de vencimento: a previsao nova precisa
  -- poder vencer de novo e acordar o responsavel outra vez.
  update public.city_events set
    status              = 'active',
    estimated_end_at    = p_new_estimated_end_at,
    overdue_notified_at = null
  where id = p_event_id;

  perform public.notify_city_event_audience(
    p_event_id, 'city_event_update', 'Previsao atualizada',
    v_event.title || ' — nova previsao registrada.', v_user
  );
end;
$$;

-- Resolve. Secao 14 do plano: e aqui que a enquete da comunidade abre.
create or replace function public.resolve_city_event(p_event_id bigint, p_message text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user  uuid := auth.uid();
  v_event public.city_events;
  v_role  text;
begin
  select * into v_event from public.city_events where id = p_event_id;
  if not found then
    raise exception 'Acontecimento nao encontrado.' using errcode = 'P0002';
  end if;

  v_role := public.city_event_role(v_user, v_event.city_id);
  if v_role is null then
    raise exception 'Sem permissao.' using errcode = '42501';
  end if;
  if v_event.status = 'resolved' then
    return;
  end if;

  update public.city_events set
    status              = 'resolved',
    resolved_at         = now(),
    resolved_by         = v_user,
    resolved_by_role    = v_role,
    overdue_notified_at = null
  where id = p_event_id;

  insert into public.city_event_updates (city_event_id, type, message, created_by, created_by_role)
  values (p_event_id, 'resolved', nullif(btrim(coalesce(p_message, '')), ''), v_user, v_role);

  perform public.notify_city_event_audience(
    p_event_id, 'city_event_resolved', v_event.title || ' — normalizado',
    coalesce(nullif(btrim(coalesce(p_message, '')), ''), 'Confirme se voltou na sua rua.'),
    v_user
  );
end;
$$;

-- Reabre. Secao 16: e o desfecho da divergencia da comunidade.
create or replace function public.reopen_city_event(
  p_event_id             bigint,
  p_new_estimated_end_at timestamptz default null,
  p_message              text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user  uuid := auth.uid();
  v_event public.city_events;
  v_role  text;
begin
  select * into v_event from public.city_events where id = p_event_id;
  if not found then
    raise exception 'Acontecimento nao encontrado.' using errcode = 'P0002';
  end if;

  v_role := public.city_event_role(v_user, v_event.city_id);
  if v_role is null then
    raise exception 'Sem permissao.' using errcode = '42501';
  end if;

  insert into public.city_event_updates (
    city_event_id, type, message, old_estimated_end_at, new_estimated_end_at, created_by, created_by_role
  ) values (
    p_event_id, 'reopened', nullif(btrim(coalesce(p_message, '')), ''),
    v_event.estimated_end_at, p_new_estimated_end_at, v_user, v_role
  );

  -- O ciclo sobe: a enquete recomeca do zero, e as respostas do ciclo anterior
  -- ficam como estao. Elas sao a razao de a reabertura ter acontecido.
  update public.city_events set
    status              = 'active',
    resolved_at         = null,
    resolved_by         = null,
    resolved_by_role    = null,
    estimated_end_at    = coalesce(p_new_estimated_end_at, estimated_end_at),
    confirmation_cycle  = confirmation_cycle + 1,
    overdue_notified_at = null
  where id = p_event_id;

  perform public.notify_city_event_audience(
    p_event_id, 'city_event_update', v_event.title || ' — reaberto',
    coalesce(nullif(btrim(coalesce(p_message, '')), ''), 'O problema voltou a ser acompanhado.'),
    v_user
  );
end;
$$;

create or replace function public.cancel_city_event(p_event_id bigint, p_message text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user  uuid := auth.uid();
  v_event public.city_events;
  v_role  text;
begin
  select * into v_event from public.city_events where id = p_event_id;
  if not found then
    raise exception 'Acontecimento nao encontrado.' using errcode = 'P0002';
  end if;

  v_role := public.city_event_role(v_user, v_event.city_id);
  if v_role is null then
    raise exception 'Sem permissao.' using errcode = '42501';
  end if;

  insert into public.city_event_updates (city_event_id, type, message, created_by, created_by_role)
  values (p_event_id, 'cancelled', nullif(btrim(coalesce(p_message, '')), ''), v_user, v_role);

  update public.city_events set status = 'cancelled' where id = p_event_id;

  -- Cancelar avisa quem foi avisado. Um alerta publicado por engano que some
  -- calado deixa a cidade achando que a falta d'agua continua.
  if v_event.status = 'active' or v_event.status = 'awaiting_confirmation' then
    perform public.notify_city_event_audience(
      p_event_id, 'city_event_update', v_event.title || ' — cancelado',
      coalesce(nullif(btrim(coalesce(p_message, '')), ''), 'O aviso foi cancelado.'),
      v_user
    );
  end if;
end;
$$;

-- ── 4.1 A confirmacao da comunidade ─────────────────────────────────────────

create or replace function public.confirm_city_event(p_event_id bigint, p_status text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user  uuid := auth.uid();
  v_event public.city_events;
begin
  if v_user is null then
    raise exception 'Entre na sua conta para responder.' using errcode = '42501';
  end if;
  if p_status not in ('resolved', 'not_resolved') then
    raise exception 'Resposta invalida.' using errcode = '22023';
  end if;

  select * into v_event from public.city_events where id = p_event_id;
  if not found then
    raise exception 'Acontecimento nao encontrado.' using errcode = 'P0002';
  end if;
  if v_event.status <> 'resolved' then
    raise exception 'A enquete abre quando o acontecimento e dado como resolvido.' using errcode = '22023';
  end if;

  insert into public.city_event_confirmations (city_event_id, user_id, cycle, status)
  values (p_event_id, v_user, v_event.confirmation_cycle, p_status)
  on conflict (city_event_id, user_id, cycle)
  do update set status = excluded.status, updated_at = now();

  perform public.check_city_event_divergence(p_event_id);
end;
$$;

-- Detecta a divergencia da secao 16 e acorda quem responde pela cidade.
--
-- O PISO DE 10 RESPOSTAS NAO E ARBITRARIO
--
-- Sem piso, as duas primeiras respostas decidem: um "ainda nao" contra um "sim"
-- da 50% e reabriria o evento com uma pessoa discordando. Dez e o menor numero
-- em que a maioria simples ainda diz alguma coisa sobre o bairro, e nao sobre
-- quem abriu o app primeiro.
--
-- E avisa UMA vez por ciclo: o gestor recebe "a comunidade discorda", decide, e
-- se decidir manter encerrado nao e perseguido a cada resposta nova.
create or replace function public.check_city_event_divergence(p_event_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event   public.city_events;
  v_sim     integer;
  v_nao     integer;
  v_total   integer;
  v_pct     integer;
begin
  select * into v_event from public.city_events where id = p_event_id;
  if not found then return false; end if;

  select
    count(*) filter (where status = 'resolved'),
    count(*) filter (where status = 'not_resolved')
  into v_sim, v_nao
  from public.city_event_confirmations
  where city_event_id = p_event_id and cycle = v_event.confirmation_cycle;

  v_total := v_sim + v_nao;
  if v_total < 10 or v_nao <= v_sim then return false; end if;

  if exists (
    select 1 from public.city_event_updates
    where city_event_id = p_event_id and type = 'community_divergence'
      and created_at > coalesce(v_event.resolved_at, v_event.created_at)
  ) then
    return false;
  end if;

  v_pct := round(100.0 * v_nao / v_total);

  insert into public.city_event_updates (city_event_id, type, message)
  values (
    p_event_id, 'community_divergence',
    v_pct || '% de ' || v_total || ' respostas dizem que ainda nao normalizou.'
  );

  perform public.notify_city_event_managers(
    p_event_id, 'city_event_divergence', 'Possivel problema persistente',
    v_pct || '% dos moradores que responderam dizem que "' || v_event.title ||
    '" ainda nao foi normalizado.'
  );

  return true;
end;
$$;

-- ── 4.2 A varredura da previsao ─────────────────────────────────────────────
--
-- Secao 12 do plano. Faz duas coisas, e nenhuma delas encerra evento (regra 4):
--
--   1. `scheduled` cujo inicio ja chegou vira `active` e avisa a audiencia;
--   2. `active` com previsao vencida vira `awaiting_confirmation` e acorda quem
--      responde pela cidade — que decide entre prorrogar e resolver.
--
-- POR QUE E IDEMPOTENTE, E POR QUE ISSO IMPORTA
--
-- Nao ha garantia de agendador neste projeto (pg_cron pode nao estar ligado no
-- plano do Supabase). Entao a funcao tambem e chamada pelo app quando um gestor
-- abre o Agora. Chamada tres vezes em um minuto, ela avisa uma so: quem ja foi
-- avisado tem `overdue_notified_at` preenchido.
create or replace function public.sweep_city_events()
returns table (publicados integer, vencidos integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id          bigint;
  v_publicados  integer := 0;
  v_vencidos    integer := 0;
  v_titulo      text;
begin
  for v_id, v_titulo in
    select id, title from public.city_events
    where status = 'scheduled' and started_at <= now()
  loop
    update public.city_events set status = 'active' where id = v_id;
    perform public.notify_city_event_audience(
      v_id, 'city_event', v_titulo, 'Comecou agora. Toque para ver a situacao.'
    );
    v_publicados := v_publicados + 1;
  end loop;

  for v_id, v_titulo in
    select id, title from public.city_events
    where status = 'active'
      and estimated_end_at is not null
      and estimated_end_at <= now()
      and overdue_notified_at is null
  loop
    update public.city_events set
      status = 'awaiting_confirmation',
      overdue_notified_at = now()
    where id = v_id;

    perform public.notify_city_event_managers(
      v_id, 'city_event_check', 'Verificar acontecimento',
      'A previsao de "' || v_titulo || '" terminou. O problema ja foi resolvido?'
    );
    v_vencidos := v_vencidos + 1;
  end loop;

  return query select v_publicados, v_vencidos;
end;
$$;

-- Agenda a varredura se o banco tiver pg_cron. Sem a extensao, o app chama a
-- funcao sozinho — a varredura ser idempotente e o que permite as duas coisas
-- coexistirem sem duplicar aviso.
do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.unschedule('sweep_city_events');
  end if;
exception when others then
  -- Nao havia agendamento anterior. E o caso normal na primeira execucao.
  null;
end $$;

do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('sweep_city_events', '*/5 * * * *', 'select public.sweep_city_events();');
  end if;
exception when others then
  raise notice 'pg_cron indisponivel; a varredura fica por conta do app.';
end $$;

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 5 — LEITURA
-- ═══════════════════════════════════════════════════════════════════════════
--
-- POR QUE RPC E NAO SELECT DIRETO
--
-- `city_event_areas.area_id` e polimorfico: aponta para `bairros` ou para
-- `pavement_streets` conforme o tipo. Nao ha FK, logo o PostgREST nao consegue
-- embutir o nome — e a tela precisa dele para escrever "Morada Nobre e mais 2
-- bairros". Sem estas funcoes, cada tela faria N consultas de rotulo.

-- Rotulo das areas de um evento, como jsonb.
create or replace function public.city_event_areas_json(p_event_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(jsonb_agg(item order by ordem, rotulo), '[]'::jsonb)
  from (
    select
      1 as ordem,
      c.name as rotulo,
      jsonb_build_object('area_type', 'city', 'area_id', null, 'label', c.name) as item
    from public.city_event_areas a
    join public.city_events e on e.id = a.city_event_id
    join public.cities c on c.id = e.city_id
    where a.city_event_id = p_event_id and a.area_type = 'city'

    union all

    select 2, b.name,
      jsonb_build_object('area_type', 'neighborhood', 'area_id', b.id, 'label', b.name)
    from public.city_event_areas a
    join public.bairros b on b.id = a.area_id
    where a.city_event_id = p_event_id and a.area_type = 'neighborhood'

    union all

    select 3, s.name,
      jsonb_build_object('area_type', 'street', 'area_id', s.id, 'label', s.name)
    from public.city_event_areas a
    join public.pavement_streets s on s.id = a.area_id
    where a.city_event_id = p_event_id and a.area_type = 'street'
  ) t;
$$;

-- A lista do Agora.
create or replace function public.get_city_events(
  p_city_id  bigint,
  p_statuses text[] default array['active', 'awaiting_confirmation', 'scheduled'],
  p_types    text[] default null,
  p_limit    integer default 50
)
returns table (
  id                 bigint,
  city_id            bigint,
  type               text,
  title              text,
  description        text,
  severity           text,
  status             text,
  started_at         timestamptz,
  estimated_end_at   timestamptz,
  resolved_at        timestamptz,
  source_name        text,
  source_url         text,
  confirmation_cycle integer,
  areas              jsonb,
  updates_count      integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    e.id, e.city_id, e.type, e.title, e.description, e.severity, e.status,
    e.started_at, e.estimated_end_at, e.resolved_at, e.source_name, e.source_url,
    e.confirmation_cycle,
    public.city_event_areas_json(e.id),
    (select count(*)::integer from public.city_event_updates u where u.city_event_id = e.id)
  from public.city_events e
  where e.city_id = p_city_id
    and e.status = any (coalesce(p_statuses, array['active', 'awaiting_confirmation', 'scheduled']))
    and (p_types is null or e.type = any (p_types))
    -- Rascunho so aparece para quem pode gerir. Um rascunho publico seria um
    -- alerta que a cidade le antes de o texto estar certo.
    and (e.status <> 'draft' or public.can_manage_city_events(auth.uid(), e.city_id))
  order by
    case e.status when 'active' then 0 when 'awaiting_confirmation' then 1
                  when 'scheduled' then 2 else 3 end,
    coalesce(e.resolved_at, e.started_at) desc
  limit greatest(1, least(coalesce(p_limit, 50), 200));
$$;

-- Um acontecimento com tudo o que a tela de detalhe mostra, numa ida so.
create or replace function public.get_city_event(p_event_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'id',                 e.id,
    'city_id',            e.city_id,
    'city_name',          c.name,
    'type',               e.type,
    'title',              e.title,
    'description',        e.description,
    'severity',           e.severity,
    'status',             e.status,
    'started_at',         e.started_at,
    'estimated_end_at',   e.estimated_end_at,
    'resolved_at',        e.resolved_at,
    'source_name',        e.source_name,
    'source_url',         e.source_url,
    'confirmation_cycle', e.confirmation_cycle,
    'can_manage',         public.can_manage_city_events(auth.uid(), e.city_id),
    'areas',              public.city_event_areas_json(e.id),
    'updates', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', u.id, 'type', u.type, 'message', u.message,
        'old_estimated_end_at', u.old_estimated_end_at,
        'new_estimated_end_at', u.new_estimated_end_at,
        'created_at', u.created_at,
        'created_by_role', u.created_by_role,
        'author_name', p.name
      ) order by u.created_at asc), '[]'::jsonb)
      from public.city_event_updates u
      left join public.profiles p on p.id = u.created_by
      where u.city_event_id = e.id
    ),
    'confirmations', (
      select jsonb_build_object(
        'resolved',     count(*) filter (where cf.status = 'resolved'),
        'not_resolved', count(*) filter (where cf.status = 'not_resolved'),
        'last_at',      max(cf.updated_at)
      )
      from public.city_event_confirmations cf
      where cf.city_event_id = e.id and cf.cycle = e.confirmation_cycle
    ),
    'my_confirmation', (
      select cf.status from public.city_event_confirmations cf
      where cf.city_event_id = e.id and cf.cycle = e.confirmation_cycle and cf.user_id = auth.uid()
    )
  )
  from public.city_events e
  join public.cities c on c.id = e.city_id
  where e.id = p_event_id
    and (e.status <> 'draft' or public.can_manage_city_events(auth.uid(), e.city_id));
$$;

-- Os acontecimentos que pegam numa rua. E o que Minha Rua consulta.
--
-- A rua e atingida pelo bairro dela ou pela cidade inteira — nunca por uma
-- linha propria. E a regra 3 do plano lida de tras para a frente.
create or replace function public.get_street_city_events(p_street_id uuid)
returns table (
  id               bigint,
  type             text,
  title            text,
  description      text,
  severity         text,
  status           text,
  started_at       timestamptz,
  estimated_end_at timestamptz,
  resolved_at      timestamptz,
  areas            jsonb
)
language sql
stable
security definer
set search_path = public
as $$
  with rua as (
    select s.id, s.bairro_id, s.city_id from public.pavement_streets s where s.id = p_street_id
  )
  select
    e.id, e.type, e.title, e.description, e.severity, e.status,
    e.started_at, e.estimated_end_at, e.resolved_at,
    public.city_event_areas_json(e.id)
  from public.city_events e
  join rua r on r.city_id = e.city_id
  where e.status in ('active', 'awaiting_confirmation')
    and exists (
      select 1 from public.city_event_areas a
      where a.city_event_id = e.id
        and (
          a.area_type = 'city'
          or (a.area_type = 'street' and a.area_id = r.id)
          or (a.area_type = 'neighborhood' and a.area_id = r.bairro_id)
        )
    )
  order by e.started_at desc;
$$;

-- O resumo do Trombone Impacto para uma cidade num periodo.
--
-- Le so o que o Agora produz. Broncas, obras e participacao ja tem contadores
-- proprios em `get_mission_counters` (migracao 198) — repetir a conta aqui
-- criaria dois numeros para a mesma pergunta.
create or replace function public.get_city_events_impact(
  p_city_id bigint,
  p_since   timestamptz default (now() - interval '30 days')
)
returns table (
  publicados      integer,
  resolvidos      integer,
  em_andamento    integer,
  confirmacoes    integer,
  participantes   integer,
  minutos_medios  integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    (select count(*)::integer from public.city_events e
      where e.city_id = p_city_id and e.started_at >= p_since and e.status <> 'draft'),
    (select count(*)::integer from public.city_events e
      where e.city_id = p_city_id and e.resolved_at >= p_since),
    (select count(*)::integer from public.city_events e
      where e.city_id = p_city_id and e.status in ('active', 'awaiting_confirmation')),
    (select count(*)::integer from public.city_event_confirmations cf
      join public.city_events e on e.id = cf.city_event_id
      where e.city_id = p_city_id and cf.created_at >= p_since),
    (select count(distinct cf.user_id)::integer from public.city_event_confirmations cf
      join public.city_events e on e.id = cf.city_event_id
      where e.city_id = p_city_id and cf.created_at >= p_since),
    (select coalesce(round(avg(extract(epoch from (e.resolved_at - e.started_at)) / 60))::integer, 0)
      from public.city_events e
      where e.city_id = p_city_id and e.resolved_at >= p_since);
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 6 — RLS
-- ═══════════════════════════════════════════════════════════════════════════

alter table public.city_events              enable row level security;
alter table public.city_event_areas         enable row level security;
alter table public.city_event_updates       enable row level security;
alter table public.city_event_confirmations enable row level security;
alter table public.user_area_follows        enable row level security;
alter table public.ambassador_areas         enable row level security;

-- city_events: publico le o que nao e rascunho; gestor escreve na sua cidade.
drop policy if exists city_events_select on public.city_events;
create policy city_events_select on public.city_events
  for select using (
    status <> 'draft' or public.can_manage_city_events(auth.uid(), city_id)
  );

drop policy if exists city_events_gestor_insert on public.city_events;
create policy city_events_gestor_insert on public.city_events
  for insert to authenticated
  with check (public.can_manage_city_events(auth.uid(), city_id));

drop policy if exists city_events_gestor_update on public.city_events;
create policy city_events_gestor_update on public.city_events
  for update to authenticated
  using (public.can_manage_city_events(auth.uid(), city_id))
  with check (public.can_manage_city_events(auth.uid(), city_id));

-- Apagar e so de admin/master. Um embaixador que erra o alerta CANCELA — o que
-- deixa rastro e avisa quem foi avisado. Apagar sumiria com a historia inteira,
-- que e o que a regra 10 proibe.
drop policy if exists city_events_admin_delete on public.city_events;
create policy city_events_admin_delete on public.city_events
  for delete to authenticated
  using (public.is_admin(auth.uid()) or public.is_master(auth.uid()));

-- city_event_areas: visivel com o evento; escrita de gestor.
drop policy if exists city_event_areas_select on public.city_event_areas;
create policy city_event_areas_select on public.city_event_areas
  for select using (
    exists (
      select 1 from public.city_events e
      where e.id = city_event_id
        and (e.status <> 'draft' or public.can_manage_city_events(auth.uid(), e.city_id))
    )
  );

drop policy if exists city_event_areas_gestor_write on public.city_event_areas;
create policy city_event_areas_gestor_write on public.city_event_areas
  for all to authenticated
  using (
    exists (select 1 from public.city_events e
            where e.id = city_event_id and public.can_manage_city_events(auth.uid(), e.city_id))
  )
  with check (
    exists (select 1 from public.city_events e
            where e.id = city_event_id and public.can_manage_city_events(auth.uid(), e.city_id))
  );

-- city_event_updates: leitura publica, insercao de gestor. Sem update, sem
-- delete — a regra 10 escrita como permissao.
drop policy if exists city_event_updates_select on public.city_event_updates;
create policy city_event_updates_select on public.city_event_updates
  for select using (
    exists (
      select 1 from public.city_events e
      where e.id = city_event_id
        and (e.status <> 'draft' or public.can_manage_city_events(auth.uid(), e.city_id))
    )
  );

drop policy if exists city_event_updates_gestor_insert on public.city_event_updates;
create policy city_event_updates_gestor_insert on public.city_event_updates
  for insert to authenticated
  with check (
    exists (select 1 from public.city_events e
            where e.id = city_event_id and public.can_manage_city_events(auth.uid(), e.city_id))
  );

-- city_event_confirmations: cada um ve e escreve a propria resposta.
--
-- O TOTAL NAO SAI DAQUI, E ISSO E DE PROPOSITO
--
-- A contagem vem de `get_city_event`, que e SECURITY DEFINER. Abrir a leitura
-- linha a linha diria QUEM respondeu "ainda nao" — numa cidade pequena, isso e
-- o vizinho descobrindo quem contrariou a prefeitura.
drop policy if exists city_event_confirmations_select_own on public.city_event_confirmations;
create policy city_event_confirmations_select_own on public.city_event_confirmations
  for select to authenticated using (user_id = auth.uid());

drop policy if exists city_event_confirmations_write_own on public.city_event_confirmations;
create policy city_event_confirmations_write_own on public.city_event_confirmations
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- user_area_follows: so o dono, em tudo.
drop policy if exists user_area_follows_own on public.user_area_follows;
create policy user_area_follows_own on public.user_area_follows
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ambassador_areas: o embaixador ve o proprio escopo; so admin/master define.
drop policy if exists ambassador_areas_select on public.ambassador_areas;
create policy ambassador_areas_select on public.ambassador_areas
  for select to authenticated
  using (user_id = auth.uid() or public.is_admin(auth.uid()) or public.is_master(auth.uid()));

drop policy if exists ambassador_areas_admin_write on public.ambassador_areas;
create policy ambassador_areas_admin_write on public.ambassador_areas
  for all to authenticated
  using (public.is_admin(auth.uid()) or public.is_master(auth.uid()))
  with check (public.is_admin(auth.uid()) or public.is_master(auth.uid()));

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 7 — GRANTS
-- ═══════════════════════════════════════════════════════════════════════════

grant select on public.city_events        to anon, authenticated;
grant select on public.city_event_areas   to anon, authenticated;
grant select on public.city_event_updates to anon, authenticated;
grant insert, update, delete on public.city_events              to authenticated;
grant insert, update, delete on public.city_event_areas         to authenticated;
grant insert                on public.city_event_updates        to authenticated;
grant select, insert, update, delete on public.city_event_confirmations to authenticated;
grant select, insert, update, delete on public.user_area_follows        to authenticated;
grant select, insert, update, delete on public.ambassador_areas         to authenticated;

-- Leitura: quem nao entrou tambem precisa saber que falta agua.
grant execute on function public.get_city_events(bigint, text[], text[], integer) to anon, authenticated;
grant execute on function public.get_city_event(bigint)                           to anon, authenticated;
grant execute on function public.get_street_city_events(uuid)                     to anon, authenticated;
grant execute on function public.city_event_areas_json(bigint)                    to anon, authenticated;
grant execute on function public.get_city_events_impact(bigint, timestamptz)      to anon, authenticated;
grant execute on function public.can_manage_city_events(uuid, bigint)             to anon, authenticated;
grant execute on function public.city_event_role(uuid, bigint)                    to authenticated;

-- Escrita: so quem entrou. Quem pode o que, cada funcao verifica sozinha.
grant execute on function public.create_city_event(bigint, text, text, jsonb, text, text, timestamptz, timestamptz, text, text, boolean, text) to authenticated;
grant execute on function public.update_city_event(bigint, text, text, text, text, timestamptz, timestamptz, text, text, jsonb) to authenticated;
grant execute on function public.publish_city_event(bigint, boolean)                to authenticated;
grant execute on function public.add_city_event_progress(bigint, text, boolean)     to authenticated;
grant execute on function public.extend_city_event(bigint, timestamptz, text)       to authenticated;
grant execute on function public.resolve_city_event(bigint, text)                   to authenticated;
grant execute on function public.reopen_city_event(bigint, timestamptz, text)       to authenticated;
grant execute on function public.cancel_city_event(bigint, text)                    to authenticated;
grant execute on function public.confirm_city_event(bigint, text)                   to authenticated;
grant execute on function public.sweep_city_events()                                to authenticated;

-- Estas nao sao chamadas pelo cliente: sao pecas internas das de cima. Sem
-- grant, o PostgREST nao as expoe — e `notify_city_event_audience` exposta
-- seria um botao de "mandar push para o bairro inteiro" com texto livre.
revoke execute on function public.city_event_audience(bigint)                              from public, anon, authenticated;
revoke execute on function public.city_event_managers(bigint)                              from public, anon, authenticated;
revoke execute on function public.notify_city_event_audience(bigint, text, text, text, uuid) from public, anon, authenticated;
revoke execute on function public.notify_city_event_managers(bigint, text, text, text, text, uuid) from public, anon, authenticated;
revoke execute on function public.set_city_event_areas(bigint, jsonb)                      from public, anon, authenticated;
revoke execute on function public.check_city_event_divergence(bigint)                      from public, anon, authenticated;
revoke execute on function public.city_event_scope_ok(uuid, bigint, jsonb)                 from public, anon, authenticated;

notify pgrst, 'reload schema';
