-- 207_fechar_o_ciclo.sql
--
-- Fase 1 do roadmap revisado (secao 36.14 do plano de gamificacao): fazer o
-- usuario enxergar o efeito da participacao.
--
-- Tres buracos, tres partes:
--
--   1. a linha do tempo nao tinha onde guardar o que o ORGAO fez;
--   2. uma atualizacao rejeitada sumia da tela sem dizer por que;
--   3. depois de 28 dias ninguem perguntava como a rua ficou.
--
-- E uma correcao de texto que nao custa coluna nenhuma: a notificacao de
-- resolucao diz "Voce fez isso acontecer", e a secao 36.5 pede o contrario —
-- uma resolucao posterior prova participacao no acompanhamento, nao causalidade
-- individual.
--
-- POR QUE report_timeline NAO E REAPROVEITADA
--
-- Ela existe, e lida por quatro telas e nunca foi escrita por nenhuma. Nao tem
-- coluna de etapa nem de proveniencia — `ReportProgress.jsx` documenta isso em
-- comentario e cai no ultimo registro como aproximacao de data. Encaixar
-- proveniencia numa tabela cujo formato ninguem conhece, com linhas historicas
-- de origem desconhecida, seria construir sobre chao que nao da para inspecionar.
-- Ela fica onde esta, intocada; o que este arquivo cria e uma tabela nova, com
-- proposito estreito: as quatro etapas que so um terceiro conhece.
--
-- O RESTO DA LINHA DO TEMPO CONTINUA DERIVADO
--
-- Registro sai de `reports`, moderacao sai de `moderation_status`, validacao e
-- verificacao saem de `report_updates` via a regra da 199. Mesma escolha da 169,
-- 198 e 199: nada de estado gravado onde o dado ja responde. `src/lib/
-- reportTimeline.js` monta a linha inteira a partir dessas fontes, e
-- `src/test/reportTimeline.test.mjs` guarda as regras.
--
-- AS POLICIES ESTAO AQUI, DE PROPOSITO
--
-- Mesma preocupacao da 206: neste projeto as policies moram no painel do
-- Supabase e nao no git, entao toda tabela nova vira regra invisivel ao codigo.
-- Toda policy das duas tabelas novas esta escrita neste arquivo.

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 1 — O QUE O ORGAO FEZ
-- ═══════════════════════════════════════════════════════════════════════════

-- Quem pode falar em nome do encaminhamento desta bronca.
--
-- Nao reaproveita `can_manage_city_events` de proposito: aquela funcao responde
-- "pode gerir acontecimentos da cidade", e um nome que responde uma pergunta
-- sendo usado para outra e como as duas divergem em silencio quando uma delas
-- mudar. A regra e a mesma hoje; a pergunta nao e.
create or replace function public.pode_registrar_etapa_oficial(p_user uuid, p_report_id uuid)
returns boolean
language plpgsql
stable
security definer
set search_path = public, extensions
as $fn$
declare
  v_city_id bigint;
begin
  if p_user is null or p_report_id is null then return false; end if;
  if public.is_admin(p_user) or public.is_master(p_user) then return true; end if;

  select city_id into v_city_id from public.reports where id = p_report_id;
  if v_city_id is null then return false; end if;

  return public.is_ambassador_of(p_user, v_city_id);
end;
$fn$;

comment on function public.pode_registrar_etapa_oficial(uuid, uuid) is
  'Admin, master ou embaixador da cidade da bronca. Quem fala com a prefeitura e quem registra o que ela respondeu.';

-- As quatro etapas que o app nao tem como deduzir.
--
-- POR QUE NAO DA PARA DERIVAR DE `status`
--
-- `reports.status` tem quatro valores (pending, in-progress, resolved,
-- duplicate) e nenhum deles distingue "o oficio saiu" de "a prefeitura
-- respondeu" de "entrou no cronograma". A barra antiga tratava 'in-progress'
-- como "Em execucao" e marcava "Em analise" como concluida por inferencia —
-- ou seja, afirmava duas coisas que ninguem havia dito.
--
-- `recusada` NAO e uma quinta etapa do caminho: e o fim de um. Fica na mesma
-- tabela porque e o mesmo fato — o que o orgao respondeu — e porque separa-la
-- faria a tela precisar unir duas fontes so para descobrir se ainda ha o que
-- esperar.
--
-- APPEND-ONLY, COMO A 206
--
-- Sem policy de update e sem policy de delete. Uma etapa registrada por engano
-- e corrigida por outra etapa; apagar sumiria com a historia, que e exatamente
-- o que uma linha do tempo com proveniencia existe para impedir.
--
-- `ocorreu_em` E DIFERENTE DE `created_at`
--
-- O oficio saiu dia 3 e o embaixador registrou dia 11. Uma coluna so obrigaria
-- a escolher entre mentir sobre o fato e mentir sobre o registro. `ocorreu_em`
-- e a hora do FATO e e o que a linha do tempo ordena; `created_at` e a hora do
-- registro e e o que a auditoria le. Mesma distincao da 194.

create table if not exists public.report_official_steps (
  id            bigint generated by default as identity primary key,
  report_id     uuid not null references public.reports(id) on delete cascade,

  etapa         text not null,
  orgao         text,
  protocolo     text,
  observacao    text,

  ocorreu_em    timestamptz not null default now(),

  registrado_por      uuid references public.profiles(id) on delete set null,
  registrado_por_papel text,

  created_at    timestamptz not null default now(),

  constraint report_official_steps_etapa_valida check (etapa in (
    'encaminhada', 'recebida', 'programada', 'executada', 'recusada'
  )),
  -- Recusa sem motivo e a mesma falha que a rejeicao muda de atualizacao: o
  -- cidadao fica sabendo que nao vai acontecer e nao fica sabendo por que.
  constraint report_official_steps_recusa_tem_motivo check (
    etapa <> 'recusada' or length(btrim(coalesce(observacao, ''))) > 0
  )
);

-- Fato no futuro nao e fato.
--
-- Gatilho e nao CHECK, pelo mesmo motivo da 193: `now()` num CHECK e avaliado
-- na insercao e nunca mais, entao a restricao mente sobre o que garante — e um
-- dump e restore reavalia tudo com o relogio de hoje e recusa linhas validas.
--
-- Um dia de folga porque relogio de celular adianta, e recusar o registro de um
-- oficio por causa disso seria perder o dado para proteger o formato.
create or replace function public.etapa_oficial_sem_futuro()
returns trigger
language plpgsql
as $fn$
begin
  if new.ocorreu_em is null or new.ocorreu_em > now() + interval '1 day' then
    new.ocorreu_em := now();
  end if;
  return new;
end;
$fn$;

drop trigger if exists a_etapa_oficial_sem_futuro on public.report_official_steps;
create trigger a_etapa_oficial_sem_futuro
before insert on public.report_official_steps
for each row execute function public.etapa_oficial_sem_futuro();

comment on table public.report_official_steps is
  'O que o orgao publico fez com a bronca. As unicas etapas da linha do tempo que o app nao consegue derivar. Espelha ETAPAS_OFICIAIS em src/lib/reportTimeline.js.';
comment on column public.report_official_steps.ocorreu_em is
  'Hora do FATO (o oficio saiu), nao do registro. A linha do tempo ordena por ela.';
comment on column public.report_official_steps.protocolo is
  'Numero do protocolo no orgao. E o que torna "encaminhada" checavel por qualquer pessoa em vez de uma palavra que a moderacao digitou.';

create index if not exists report_official_steps_por_bronca_idx
  on public.report_official_steps (report_id, ocorreu_em desc);

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 2 — REJEICAO QUE EXPLICA
-- ═══════════════════════════════════════════════════════════════════════════
--
-- HOJE A ATUALIZACAO REJEITADA SIMPLESMENTE DESAPARECE
--
-- `ModerationPage` grava `status = 'rejected'` e manda uma notificacao com uma
-- frase fixa: "nao foi aprovada por nao cumprir as diretrizes". Qual diretriz,
-- nao diz. `ReportPage` filtra a linha da lista — inclusive para o proprio
-- autor — e `ReportUpdates.jsx` chega a calcular `isRejected` e nunca usa.
--
-- Do lado de quem enviou, a experiencia inteira e: mandei uma foto, ganhei um
-- aviso generico, a atualizacao sumiu e nao ha o que fazer a respeito.
--
-- A bronca ja resolveu isso ha tempos — `reports` tem rejection_title,
-- rejection_description e rejected_at, e a moderacao exige os dois textos. A
-- atualizacao ficou para tras. Esta parte iguala as duas.
--
-- MOTIVO ESTRUTURADO, NAO SO TEXTO LIVRE
--
-- O texto livre resolve o caso individual e nao resolve o produto: nao da para
-- contar quantas rejeicoes sao de foto ilegivel, e sem contar nao da para
-- consertar o formulario que produz foto ilegivel. O codigo estruturado e o que
-- torna a rejeicao um dado de qualidade em vez de uma frase.
--
-- Os codigos espelham MOTIVOS_DE_REJEICAO em src/lib/reportRejection.js.

alter table public.report_updates
  add column if not exists rejection_reason text,
  add column if not exists rejection_note   text,
  add column if not exists rejected_at      timestamptz,
  add column if not exists rejected_by      uuid references public.profiles(id) on delete set null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'report_updates_motivo_de_rejeicao_valido'
      and conrelid = 'public.report_updates'::regclass
  ) then
    -- NOT VALID: as linhas rejeitadas antes desta migracao nao tem motivo, e
    -- apagar ou inventar o motivo delas seria reescrever o passado por causa de
    -- um criterio novo. A regra vale para toda linha nova.
    alter table public.report_updates
      add constraint report_updates_motivo_de_rejeicao_valido
      check (
        rejection_reason is null or rejection_reason in (
          'fora_do_local', 'sem_evidencia', 'evidencia_ilegivel', 'nao_corresponde',
          'duplicada', 'conteudo_improprio', 'dado_pessoal', 'outro'
        )
      ) not valid;
  end if;
end $$;

comment on column public.report_updates.rejection_reason is
  'Codigo do motivo. Espelha MOTIVOS_DE_REJEICAO em src/lib/reportRejection.js; existe para a rejeicao virar dado de qualidade, nao so frase.';
comment on column public.report_updates.rejection_note is
  'O que o moderador escreveu para esta pessoa. E a metade que ensina.';

-- A notificacao da rejeicao, com o motivo dentro.
--
-- Sai do cliente e vem para o banco pelo mesmo motivo da 199: hoje quem escreve
-- a notificacao e `ModerationPage`, e um segundo lugar que rejeite atualizacao
-- (uma tela de embaixador, um script) esquece de avisar sem que nada acuse.
--
-- Nao substitui o texto do moderador: o `rejection_note` e o que a pessoa mais
-- precisa ler, e o codigo do motivo entra so quando nao ha nota.
create or replace function public.notificar_rejeicao_de_atualizacao()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $fn$
declare
  v_titulo text;
  v_motivo text;
begin
  if new.status <> 'rejected' or coalesce(old.status, '') = 'rejected' then
    return new;
  end if;
  if new.author_id is null then
    return new;
  end if;

  select title into v_titulo from public.reports where id = new.report_id;

  v_motivo := coalesce(
    nullif(btrim(new.rejection_note), ''),
    case new.rejection_reason
      when 'fora_do_local'      then 'A foto ou o relato nao parece ser do local da bronca.'
      when 'sem_evidencia'      then 'Faltou evidencia do que voce descreveu.'
      when 'evidencia_ilegivel' then 'A foto nao permite ver o que foi relatado.'
      when 'nao_corresponde'    then 'O que foi relatado nao corresponde ao problema desta bronca.'
      when 'duplicada'          then 'Esta mesma informacao ja havia sido enviada.'
      when 'conteudo_improprio' then 'O conteudo enviado nao cumpre as diretrizes.'
      when 'dado_pessoal'       then 'A imagem ou o texto expunha dado pessoal de alguem.'
      else 'A atualizacao nao foi aprovada.'
    end
  );

  insert into public.notifications (user_id, type, title, message, link, report_id, is_read, created_at)
  values (
    new.author_id,
    'status_update',
    'Sua atualizacao nao foi publicada',
    v_motivo || ' Voce pode corrigir e reenviar em "' || coalesce(v_titulo, 'a bronca') || '".',
    '/bronca/' || new.report_id,
    new.report_id,
    false,
    now()
  );

  return new;
end;
$fn$;

drop trigger if exists on_report_update_rejeitada on public.report_updates;
create trigger on_report_update_rejeitada
after update of status on public.report_updates
for each row execute function public.notificar_rejeicao_de_atualizacao();

comment on function public.notificar_rejeicao_de_atualizacao() is
  'Avisa quem enviou, com o motivo e o caminho de correcao. Uma rejeicao bem explicada preserva confianca; uma rejeicao silenciosa gasta.';

-- ── A atualizacao rejeitada volta a ser visivel PARA QUEM A ENVIOU ──────────
--
-- Precisa existir no banco, nao so na tela: `ReportPage` esconde a linha, mas
-- se a policy de select tambem escondesse, o cliente nunca teria o que mostrar.
-- Para os outros ela continua invisivel — uma rejeicao e uma conversa entre a
-- moderacao e quem enviou, nao um aviso publico sobre a pessoa.
--
-- Esta policy e ADITIVA: policies de select se somam por OR, entao a policy que
-- ja existe (e que mora no painel) continua valendo para todo o resto.
drop policy if exists report_updates_autor_ve_a_propria_rejeitada on public.report_updates;
create policy report_updates_autor_ve_a_propria_rejeitada on public.report_updates
  for select to authenticated
  using (author_id = auth.uid());

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 3 — A REVISITA DE 28 DIAS
-- ═══════════════════════════════════════════════════════════════════════════
--
-- "Faz 28 dias que voce registrou este problema. Como ele esta agora?"
--
-- POR QUE 28 DIAS, E POR QUE OPT-IN
--
-- E o intervalo do FixMyStreet, e a escolha por tras dele importa mais que o
-- numero: e uma alternativa a exigir uso diario. O produto pergunta uma vez,
-- por bronca, e a pessoa decide se quer ser perguntada de novo. Participacao
-- episodica e legitima (principio 13); o app nao fabrica culpa.
--
-- ESTA TABELA NAO GUARDA A RESPOSTA DE CAMPO
--
-- "Continua igual", "melhorou" e "foi resolvido" viram linha de
-- `report_updates`, que e onde toda observacao de campo mora — e assim a
-- resposta da revisita passa pelas MESMAS regras: moderacao, limite semanal,
-- quorum da 199, credito de Impacto da 198. Uma segunda tabela de observacao
-- seria uma segunda verdade sobre o estado da rua.
--
-- O que fica aqui e so o que a `report_updates` nao sabe responder: a quem
-- perguntamos, quando, o que a pessoa respondeu ao convite (inclusive "nao
-- consigo verificar", que nao gera observacao nenhuma) e se ela quer o proximo
-- lembrete.

create table if not exists public.report_revisits (
  id                bigint generated by default as identity primary key,
  report_id         uuid not null references public.reports(id) on delete cascade,
  user_id           uuid not null references public.profiles(id) on delete cascade,

  perguntada_em     timestamptz not null default now(),
  respondida_em     timestamptz,
  resposta          text,

  -- Null = ainda nao disse. False = pediu para nao perguntar de novo NESTA
  -- bronca. A ausencia de resposta nao pode virar "nao quer": quem ignorou um
  -- convite nao optou por nada.
  quer_lembrete     boolean,

  report_update_id  uuid references public.report_updates(id) on delete set null,

  created_at        timestamptz not null default now(),

  constraint report_revisits_resposta_valida check (
    resposta is null or resposta in (
      'igual', 'piorou', 'melhorou', 'resolvido', 'nao_consigo_verificar'
    )
  ),
  constraint report_revisits_resposta_tem_data check (
    (resposta is null) = (respondida_em is null)
  )
);

comment on table public.report_revisits is
  'Convite de microatualizacao apos 28 dias. Guarda o CONVITE; a observacao de campo vira report_updates, para passar pelas mesmas regras.';
comment on column public.report_revisits.quer_lembrete is
  'Null = nao disse. False = nao perguntar de novo nesta bronca. Ausencia de resposta nunca vira recusa.';

-- Uma pergunta aberta por pessoa e por bronca. Sem isto, abrir a tela duas
-- vezes cria dois convites e a mesma pessoa e perguntada em dobro.
create unique index if not exists report_revisits_uma_aberta_por_pessoa
  on public.report_revisits (report_id, user_id)
  where respondida_em is null;

create index if not exists report_revisits_por_pessoa_idx
  on public.report_revisits (user_id, perguntada_em desc);

-- Quem deve ser convidado agora.
--
-- Devolve so o que a tela precisa para montar o convite. As condicoes sao todas
-- de exclusao, e cada uma existe por um motivo:
--
--   • bronca aberta — perguntar "como esta?" sobre algo ja verificado e ruido;
--   • aprovada — bronca recusada nao tem o que revisitar;
--   • 28 dias desde o ULTIMO fato conhecido, nao desde o registro: uma bronca
--     atualizada ontem nao esta parada ha 28 dias;
--   • ninguem ja convidado nesta bronca com convite em aberto;
--   • ninguem que pediu para nao ser perguntado de novo AQUI.
create or replace function public.revisitas_pendentes(p_user uuid, p_limite integer default 3)
returns table (
  report_id    uuid,
  titulo       text,
  endereco     text,
  registrada_em timestamptz,
  dias_parada  integer
)
language sql
stable
security definer
set search_path = public, extensions
as $fn$
  select
    r.id,
    r.title,
    r.address,
    r.created_at,
    extract(day from now() - greatest(
      r.created_at,
      coalesce((select max(u.created_at) from public.report_updates u
                where u.report_id = r.id and coalesce(u.status,'') <> 'rejected'), r.created_at)
    ))::integer
  from public.reports r
  where r.author_id = p_user
    and r.status in ('pending', 'in-progress')
    and coalesce(r.moderation_status, 'approved') = 'approved'
    and greatest(
      r.created_at,
      coalesce((select max(u.created_at) from public.report_updates u
                where u.report_id = r.id and coalesce(u.status,'') <> 'rejected'), r.created_at)
    ) < now() - interval '28 days'
    and not exists (
      select 1 from public.report_revisits rv
      where rv.report_id = r.id
        and rv.user_id = p_user
        and (rv.respondida_em is null or rv.quer_lembrete is false)
    )
  order by r.created_at
  limit greatest(1, least(coalesce(p_limite, 3), 10));
$fn$;

comment on function public.revisitas_pendentes(uuid, integer) is
  'Broncas do proprio usuario paradas ha 28 dias, sem convite em aberto e sem recusa de lembrete. Opt-in por bronca.';

grant execute on function public.revisitas_pendentes(uuid, integer) to authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 4 — NOTIFICACAO POR MUDANCA REAL DE ESTADO
-- ═══════════════════════════════════════════════════════════════════════════

-- Uma etapa oficial nova e a definicao de mudanca real de estado: alguem fora
-- do app fez alguma coisa. Vai para todos os participantes, pelo mesmo motivo
-- da 199 — quem confirmou em campo fez o trabalho que sustenta a verificacao.
--
-- E DELIBERADAMENTE CAUTELOSA NO TEXTO
--
-- "Encaminhada ao orgao" nao pode chegar no aparelho parecendo "resolvido". O
-- corpo diz o que falta, nao o que foi conquistado.
create or replace function public.notificar_etapa_oficial()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $fn$
declare
  v_onde   text;
  v_titulo text;
  v_corpo  text;
begin
  select coalesce(nullif(btrim(r.address), ''), nullif(btrim(r.title), ''),
                  'Uma bronca que voce acompanha')
    into v_onde
  from public.reports r where r.id = new.report_id;

  v_titulo := case new.etapa
    when 'encaminhada' then 'Encaminhada ao orgao responsavel'
    when 'recebida'    then 'O orgao confirmou o recebimento'
    when 'programada'  then 'Entrou na programacao do orgao'
    when 'executada'   then 'O orgao informou execucao'
    when 'recusada'    then 'O orgao recusou a solicitacao'
  end;

  v_corpo := case new.etapa
    when 'executada'
      then left(v_onde, 80) || '. Ninguem confirmou no local ainda — se voce passar por la, diga como esta.'
    when 'recusada'
      then left(v_onde, 80) || '. Motivo: ' || coalesce(nullif(btrim(new.observacao), ''), 'nao informado') || '.'
    else
      left(v_onde, 80) || '. Encaminhar nao e resolver: a execucao depende do orgao publico.'
  end;

  insert into public.notifications (user_id, type, title, message, link, report_id, is_read, created_at)
  select p.user_id, 'status_update', v_titulo, v_corpo,
         '/bronca/' || new.report_id, new.report_id, false, now()
  from public.report_participants(new.report_id) p;

  return new;
end;
$fn$;

drop trigger if exists on_etapa_oficial_notify on public.report_official_steps;
create trigger on_etapa_oficial_notify
after insert on public.report_official_steps
for each row execute function public.notificar_etapa_oficial();

comment on function public.notificar_etapa_oficial() is
  'Avisa os participantes quando o orgao mexe. O texto nunca deixa "encaminhada" soar como "resolvida".';

-- ── A correcao de texto da resolucao ────────────────────────────────────────
--
-- A 199 escreveu "Voce fez isso acontecer." A secao 36.5 do plano pede o
-- contrario, e a razao e de honestidade, nao de tom: uma bronca resolvida
-- depois prova que a pessoa registrou, verificou e acompanhou. Nao prova,
-- sozinha, que ela causou o conserto — quem consertou foi quem foi la com a
-- maquina.
--
-- Prometer causalidade individual e o tipo de exagero que funciona uma vez e
-- corroi a credibilidade do placar inteiro depois. Espelha `fraseDaResolucao`
-- em src/lib/impact.js, que muda junto.
create or replace function public.notificar_resolucao()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $fn$
declare
  v_total integer;
  v_onde  text;
begin
  if new.status is not distinct from old.status or new.status <> 'resolved' then
    return new;
  end if;

  select count(*) into v_total from public.report_participants(new.id);
  v_onde := coalesce(nullif(trim(new.address), ''), nullif(trim(new.title), ''),
                     'Um problema que voce acompanhava');

  insert into public.notifications (user_id, type, title, message, link, is_read, created_at)
  select
    p.user_id,
    'status_update',
    left(v_onde, 80) || ' foi resolvido',
    case
      when v_total <= 1 then 'Voce contribuiu para registrar, verificar e acompanhar esta solucao.'
      when v_total = 2  then 'Voce e mais 1 pessoa acompanharam este problema ate o fim.'
      else 'Voce e mais ' || (v_total - 1) || ' pessoas acompanharam este problema ate o fim.'
    end,
    '/bronca/' || new.id,
    false,
    now()
  from public.report_participants(new.id) p;

  return new;
end;
$fn$;

comment on function public.notificar_resolucao() is
  'Avisa todos os participantes quando a bronca fecha. Reconhece participacao no acompanhamento, nao causalidade individual (secao 36.5). Espelha fraseDaResolucao em src/lib/impact.js.';

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 5 — RLS
-- ═══════════════════════════════════════════════════════════════════════════

alter table public.report_official_steps enable row level security;
alter table public.report_revisits       enable row level security;

-- Etapa oficial: leitura publica (e a proveniencia que a linha do tempo mostra
-- para qualquer um), escrita so de quem responde pela cidade.
drop policy if exists report_official_steps_select on public.report_official_steps;
create policy report_official_steps_select on public.report_official_steps
  for select using (true);

drop policy if exists report_official_steps_gestor_insert on public.report_official_steps;
create policy report_official_steps_gestor_insert on public.report_official_steps
  for insert to authenticated
  with check (
    public.pode_registrar_etapa_oficial(auth.uid(), report_id)
    and registrado_por = auth.uid()
  );

-- Sem update e sem delete, de proposito: append-only, igual a city_event_updates
-- da 206. Etapa errada se corrige com outra etapa.

-- Revisita: cada um ve e escreve a propria. Ninguem precisa saber que o vizinho
-- foi convidado a revisitar e nao respondeu.
drop policy if exists report_revisits_own on public.report_revisits;
create policy report_revisits_own on public.report_revisits
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 6 — GRANTS
-- ═══════════════════════════════════════════════════════════════════════════

grant select, insert on public.report_official_steps to authenticated;
grant select on public.report_official_steps to anon;
grant select, insert, update on public.report_revisits to authenticated;
grant usage, select on sequence public.report_official_steps_id_seq to authenticated;
grant usage, select on sequence public.report_revisits_id_seq to authenticated;

notify pgrst, 'reload schema';
