-- 213_cobertura_e_cooperacao.sql
--
-- Fase 3 do roadmap revisado (secao 36.14): provar valor coletivo em um
-- territorio limitado.
--
-- UM PILOTO, NAO DOIS
--
-- A fase pede "piloto de pavimentacao OU obras, nao os dois ao mesmo tempo".
-- Esta migracao faz pavimentacao, e a escolha nao e de gosto: o traçado das
-- ruas ja existe (`pavement_streets.path`, migracao 203), a base ja tem dono
-- (embaixador, migracoes 152 e 153), e a pergunta cabe numa frase. Obras
-- dependeriam de medicao, cronograma e percentual oficial — coisas que o
-- cidadao nao pode declarar sozinho, e que fariam o piloto comecar pelo caso
-- dificil.
--
-- O CIDADAO SUGERE. QUEM ALTERA E O EMBAIXADOR.
--
-- E a regra que define o desenho inteiro (secao 36.7). Nao existe caminho neste
-- arquivo em que uma linha de `pavement_suggestions` mude `pavement_streets`
-- sozinha: nem trigger, nem RPC, nem policy. A alteracao e um UPDATE feito por
-- quem ja tinha permissao de fazer UPDATE antes desta migracao existir.
--
-- POR QUE A COBERTURA NAO E CALCULADA NO BANCO
--
-- Mesma escolha da 212: `src/lib/cobertura.js` tem os cinco estados e a regra
-- de "duas pessoas independentes". A RPC daqui devolve as ruas com as sugestoes
-- que valem, e o cliente decide. Duas implementacoes da mesma regra divergem, e
-- a primeira vez que discordassem sobre quantas ruas estao cobertas seria
-- dentro de um relatorio publico.
--
-- AS POLICIES ESTAO AQUI — mesma razao da 206, 207 e 212.

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 1 — PAVIMENTACAO CIDADA
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists public.pavement_suggestions (
  id            bigint generated by default as identity primary key,
  street_id     uuid not null references public.pavement_streets(id) on delete cascade,
  user_id       uuid not null references public.profiles(id) on delete cascade,

  -- Uma pergunta so, por enquanto. O CHECK e o que impede o piloto de virar um
  -- editor de cadastro por acrescimo — alterar nome, traçado, CEP ou legislacao
  -- nao pertence a este fluxo (secao 36.7).
  pergunta      text not null default 'classificacao',
  resposta      text not null,

  -- De onde a pessoa respondeu. Colunas soltas e nao geometry: nao ha consulta
  -- espacial sobre elas, sao lidas uma vez pelo gatilho, e guardar o ponto como
  -- geometria indexada seria manter mais dado de localizacao do que o
  -- necessario (secao 36.9 — menor tempo e precisao necessarios).
  lat           double precision,
  lng           double precision,

  -- Preenchidas pelo gatilho, nao pelo cliente. Ver `checar_local_da_sugestao`.
  distancia_m   double precision,
  local_confere boolean,

  observacao    text,
  status        text not null default 'pendente',

  aprovada_por  uuid references public.profiles(id) on delete set null,
  aprovada_em   timestamptz,

  created_at    timestamptz not null default now(),

  constraint pavement_suggestions_pergunta_valida check (pergunta in ('classificacao')),
  -- Espelha RESPOSTAS_DE_PAVIMENTO em src/lib/sugestaoPavimento.js, que por sua
  -- vez espelha STATUS_DE_RUA em src/lib/pavementReport.js. Os tres precisam
  -- concordar: a resposta aprovada vira `pavement_streets.status` literalmente.
  constraint pavement_suggestions_resposta_valida check (
    resposta in ('paved', 'partially_paved', 'unpaved')
  ),
  constraint pavement_suggestions_status_valido check (
    status in ('pendente', 'aprovada', 'recusada')
  )
);

comment on table public.pavement_suggestions is
  'Sugestao de classificacao de rua enviada por cidadao. NUNCA altera pavement_streets: a alteracao e um UPDATE do embaixador, no passo seguinte (secao 36.7).';
comment on column public.pavement_suggestions.local_confere is
  'Se a pessoa estava na rua ao responder. Calculado pelo gatilho contra o traçado; sugestao de longe nao conta como observacao de campo.';

-- Uma resposta por pessoa por rua, por semana.
--
-- Nao "uma para sempre": a rua muda, e quem verificou em marco pode verificar
-- de novo em outubro. Nao "sem limite": duas linhas do mesmo autor no mesmo dia
-- fariam uma pessoa sozinha parecer duas na contagem de cobertura — o cliente
-- ja deduplica por autor, mas defesa que so existe no cliente nao e defesa.
create unique index if not exists pavement_suggestions_uma_por_semana
  on public.pavement_suggestions (
    street_id, user_id, (date_trunc('week', created_at at time zone 'America/Sao_Paulo'))
  );

create index if not exists pavement_suggestions_por_rua_idx
  on public.pavement_suggestions (street_id, created_at desc);

create index if not exists pavement_suggestions_fila_idx
  on public.pavement_suggestions (status, created_at)
  where status = 'pendente';

-- ── A checagem automatica de local ──────────────────────────────────────────
--
-- Segundo passo do fluxo da secao 36.7, e o unico que o cliente nao pode fazer:
-- a distancia ate um MULTILINESTRING e conta de PostGIS, e a coordenada enviada
-- pelo app e texto no corpo da requisicao — qualquer um a edita.
--
-- Mesma logica da regra dos 100 m da 173: o cliente checa para nao oferecer o
-- que sera recusado; o servidor checa porque e ele quem protege o dado.
--
-- Rua sem traçado cai no ponto (`location`). Rua sem nenhum dos dois fica com
-- `local_confere` nulo — "nao sabemos", que e diferente de "confere" e de "nao
-- confere", e o cliente trata nulo como nao-conferido para efeito de cobertura.
create or replace function public.checar_local_da_sugestao()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $fn$
declare
  v_geom  extensions.geometry;
  v_ponto extensions.geometry;
  v_raio  double precision := 60;  -- espelha RAIO_DE_OBSERVACAO_M
begin
  if new.lat is null or new.lng is null then
    new.local_confere := null;
    return new;
  end if;

  select coalesce(s.path::extensions.geometry, s.location::extensions.geometry)
    into v_geom
  from public.pavement_streets s
  where s.id = new.street_id;

  if v_geom is null then
    new.local_confere := null;
    return new;
  end if;

  v_ponto := extensions.st_setsrid(extensions.st_makepoint(new.lng, new.lat), 4326);

  new.distancia_m := extensions.st_distance(
    v_geom::extensions.geography,
    v_ponto::extensions.geography
  );
  new.local_confere := new.distancia_m <= v_raio;

  return new;
end;
$fn$;

comment on column public.pavement_suggestions.lat is
  'Latitude de onde a pessoa respondeu. Usada uma vez, pelo gatilho, para medir a distancia ate a rua.';

drop trigger if exists a_pavement_suggestion_local on public.pavement_suggestions;
create trigger a_pavement_suggestion_local
before insert on public.pavement_suggestions
for each row execute function public.checar_local_da_sugestao();

-- ── As ruas de uma area, com o que a cobertura precisa ──────────────────────
--
-- Devolve as sugestoes como jsonb pelo mesmo motivo da 212: a regra de cobertura
-- mora em `src/lib/cobertura.js`, e reimplementa-la aqui criaria duas verdades
-- sobre quantas ruas estao verificadas.
--
-- Sem `user_id` no retorno? Nao: ele PRECISA vir, porque "duas pessoas
-- independentes" e contado por autor distinto. O que nao vem e nome — a
-- cobertura nao e um placar de quem verificou o que.
create or replace function public.cobertura_de_area(
  p_city_id   bigint,
  p_bairro_ids uuid[] default null
)
returns table (
  id          uuid,
  name        text,
  status      text,
  bairro_id   uuid,
  bairro_nome text,
  sugestoes   jsonb
)
language sql
stable
security definer
set search_path = public, extensions
as $fn$
  select
    s.id,
    s.name,
    s.status,
    s.bairro_id,
    b.name,
    coalesce(
      (
        select jsonb_agg(jsonb_build_object(
                 'user_id',       g.user_id,
                 'street_id',     g.street_id,
                 'resposta',      g.resposta,
                 'status',        g.status,
                 'local_confere', g.local_confere,
                 'created_at',    g.created_at
               ))
        from public.pavement_suggestions g
        where g.street_id = s.id
          and g.status <> 'recusada'
          -- Um ano cobre com folga a janela de 180 dias de
          -- JANELA_COBERTURA_DIAS, sem carregar o historico inteiro da rua.
          and g.created_at >= now() - interval '1 year'
      ),
      '[]'::jsonb
    )
  from public.pavement_streets s
  left join public.bairros b on b.id = s.bairro_id
  where s.city_id = p_city_id
    and (p_bairro_ids is null or s.bairro_id = any(p_bairro_ids))
  order by b.name nulls last, s.name;
$fn$;

comment on function public.cobertura_de_area(bigint, uuid[]) is
  'Ruas de uma area com as sugestoes que valem, para src/lib/cobertura.js calcular os cinco estados. O banco nao decide o estado: a regra mora num lugar so.';

grant execute on function public.cobertura_de_area(bigint, uuid[]) to authenticated;
grant execute on function public.cobertura_de_area(bigint, uuid[]) to anon;

-- ── Auditoria tambem vale para RUA ──────────────────────────────────────────
--
-- A 212 criou `report_audit_requests` presumindo que todo pedido de auditoria
-- fosse sobre uma bronca. A pavimentacao cidada quebra essa premissa no primeiro
-- uso: quem esta na rua ve que o NOME esta errado, que o traçado passa na quadra
-- de cima, que o CEP nao bate — e nada disso e bronca.
--
-- A alternativa seria uma segunda tabela de auditoria. Seria pior: duas filas
-- para a mesma pessoa olhar, com dois lugares para esquecer de olhar. O pedido e
-- o mesmo — "alguem confira este cadastro" —, muda so o que se aponta.
--
-- `report_id` passa a aceitar nulo, e o CHECK garante que exatamente um alvo
-- esta preenchido. Sem ele, um pedido sem alvo nenhum entraria na fila e ficaria
-- la para sempre, porque ninguem saberia o que abrir.

alter table public.report_audit_requests
  alter column report_id drop not null,
  add column if not exists street_id uuid references public.pavement_streets(id) on delete cascade;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'report_audit_requests_um_alvo'
      and conrelid = 'public.report_audit_requests'::regclass
  ) then
    alter table public.report_audit_requests
      add constraint report_audit_requests_um_alvo
      check (num_nonnulls(report_id, street_id) = 1);
  end if;
end $$;

comment on column public.report_audit_requests.street_id is
  'Alvo alternativo ao report_id: pedido de auditoria sobre o CADASTRO de uma rua (nome, traçado, CEP), vindo da pavimentacao cidada.';

-- O indice de "sem repeticao" da 212 so cobria report_id. Com dois alvos
-- possiveis, ele deixava passar dez pedidos da mesma pessoa sobre a mesma rua.
create unique index if not exists report_audit_requests_rua_sem_repeticao
  on public.report_audit_requests (street_id, user_id, motivo)
  where status = 'aberta' and street_id is not null;

-- A policy de leitura da 212 so olhava `reports`. Um pedido sobre rua ficaria
-- visivel apenas para quem o abriu — invisivel exatamente para quem deve
-- resolve-lo.
drop policy if exists report_audit_requests_select on public.report_audit_requests;
create policy report_audit_requests_select on public.report_audit_requests
  for select to authenticated
  using (
    user_id = auth.uid()
    or public.is_admin(auth.uid())
    or public.is_master(auth.uid())
    or exists (
      select 1 from public.reports r
      where r.id = report_id
        and r.city_id is not null
        and public.is_ambassador_of(auth.uid(), r.city_id)
    )
    or exists (
      select 1 from public.pavement_streets s
      where s.id = street_id
        and s.city_id is not null
        and public.is_ambassador_of(auth.uid(), s.city_id)
    )
  );

drop policy if exists report_audit_requests_moderacao_update on public.report_audit_requests;
create policy report_audit_requests_moderacao_update on public.report_audit_requests
  for update to authenticated
  using (
    public.is_admin(auth.uid())
    or public.is_master(auth.uid())
    or exists (
      select 1 from public.reports r
      where r.id = report_id
        and r.city_id is not null
        and public.is_ambassador_of(auth.uid(), r.city_id)
    )
    or exists (
      select 1 from public.pavement_streets s
      where s.id = street_id
        and s.city_id is not null
        and public.is_ambassador_of(auth.uid(), s.city_id)
    )
  )
  with check (true);

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 2 — A META COMUNITARIA
-- ═══════════════════════════════════════════════════════════════════════════
--
-- "Atualizar a situacao de 80% das ruas no entorno de duas escolas" (36.7).
--
-- POR QUE A AREA E UMA LISTA DE BAIRROS, E NAO UM POLIGONO
--
-- Poligono desenhado a mao seria mais preciso e pior: ninguem sabe se mora
-- dentro dele. Bairro e a unidade que a pessoa usa para dizer onde mora, e ja e
-- a unidade de `pavement_streets.bairro_id` — o que torna o denominador da meta
-- uma consulta, nao um recorte novo.
--
-- Quando o entorno de duas escolas nao coincidir com um bairro inteiro, a meta
-- cobre o bairro. Uma meta um pouco maior que o desenhado e honesta; um
-- poligono que ninguem sabe conferir nao e.
--
-- SEM COLUNA DE PROGRESSO
--
-- O progresso e derivado (`progressoDaMeta`, em src/lib/metaComunitaria.js). Uma
-- coluna `ruas_cobertas` precisaria de trigger em pavement_suggestions e ficaria
-- errada no dia em que a janela de 180 dias vencesse uma verificacao antiga —
-- que e um evento que acontece sem nenhum INSERT para dispara-lo.

create table if not exists public.community_goals (
  id              bigint generated by default as identity primary key,
  city_id         bigint not null references public.cities(id) on delete cascade,

  titulo          text not null,
  descricao       text,
  bairro_ids      uuid[] not null default '{}',

  alvo_percentual integer not null default 80,

  inicio          date not null default (now() at time zone 'America/Sao_Paulo')::date,
  fim             date,

  status          text not null default 'rascunho',

  -- O relatorio publico e parte da meta, nao um extra (entrega da fase 3). Duas
  -- colunas porque as perguntas sao diferentes: o que foi PRODUZIDO sai dos
  -- dados; o que foi USADO so alguem sabe.
  uso_texto       text,
  uso_registrado_em timestamptz,

  criada_por      uuid references public.profiles(id) on delete set null,
  created_at      timestamptz not null default now(),

  constraint community_goals_status_valido check (
    status in ('rascunho', 'aberta', 'encerrada')
  ),
  constraint community_goals_alvo_valido check (alvo_percentual between 10 and 100),
  constraint community_goals_area_nao_vazia check (
    status = 'rascunho' or array_length(bairro_ids, 1) >= 1
  ),
  constraint community_goals_fim_depois_do_inicio check (fim is null or fim >= inicio)
);

comment on table public.community_goals is
  'Meta comunitaria de cobertura numa area definida. Progresso e derivado em src/lib/metaComunitaria.js — nao ha coluna de contagem.';
comment on column public.community_goals.uso_texto is
  'O que o poder publico fez com o dado. Enquanto for nulo, o relatorio publico DIZ que nao ha registro de uso, em vez de omitir a secao.';

create index if not exists community_goals_por_cidade_idx
  on public.community_goals (city_id, status, inicio desc);

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 3 — O MUTIRAO
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Os sete requisitos da secao 36.7 sao NOT NULL na publicacao, nao conselhos.
-- Escrito como recomendacao, esse tipo de lista sobrevive ao primeiro mutirao e
-- some no terceiro, quando alguem esta com pressa — e o custo de esquecer nao e
-- simetrico: um mutirao sem canal de suporte e um grupo de pessoas na rua sem
-- para quem ligar.
--
-- O CHECK vale so para status <> 'rascunho'. Rascunho existe justamente para o
-- organizador montar aos poucos; o que nao pode e um rascunho incompleto virar
-- convite publico.

create table if not exists public.mutiroes (
  id                 bigint generated by default as identity primary key,
  city_id            bigint not null references public.cities(id) on delete cascade,
  community_goal_id  bigint references public.community_goals(id) on delete set null,

  titulo             text not null,
  organizador_id     uuid references public.profiles(id) on delete set null,

  area_descricao     text,
  ponto_de_encontro  text,
  orientacao         text,
  canal_suporte      text,
  objetivo_dados     text,
  alternativa_remota text,

  inicio_em          timestamptz,
  fim_em             timestamptz,

  status             text not null default 'rascunho',
  relatorio_publico  text,

  created_at         timestamptz not null default now(),

  constraint mutiroes_status_valido check (
    status in ('rascunho', 'publicado', 'encerrado', 'cancelado')
  ),

  -- Os sete, cobrados na publicacao. Espelha REQUISITOS em src/lib/mutirao.js.
  constraint mutiroes_requisitos_para_publicar check (
    status = 'rascunho'
    or status = 'cancelado'
    or (
      organizador_id     is not null
      and length(btrim(coalesce(area_descricao, '')))     > 0
      and length(btrim(coalesce(ponto_de_encontro, '')))  > 0
      and length(btrim(coalesce(orientacao, '')))         > 0
      and length(btrim(coalesce(canal_suporte, '')))      > 0
      and length(btrim(coalesce(objetivo_dados, '')))     > 0
      and length(btrim(coalesce(alternativa_remota, ''))) > 0
      and inicio_em is not null
    )
  ),

  -- O oitavo, cobrado no encerramento. Um mutirao que some da tela sem dizer o
  -- que produziu ensina que o esforco nao e contabilizado.
  constraint mutiroes_encerrado_tem_relatorio check (
    status <> 'encerrado' or length(btrim(coalesce(relatorio_publico, ''))) > 0
  )
);

comment on table public.mutiroes is
  'Mutirao presencial. Os sete requisitos da secao 36.7 sao CHECK na publicacao e o relatorio publico e CHECK no encerramento — nao sao texto de ajuda.';

create index if not exists mutiroes_por_cidade_idx
  on public.mutiroes (city_id, status, inicio_em desc);

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 4 — RLS
-- ═══════════════════════════════════════════════════════════════════════════

alter table public.pavement_suggestions enable row level security;
alter table public.community_goals      enable row level security;
alter table public.mutiroes             enable row level security;

-- Sugestoes: leitura publica (a cobertura e informacao da cidade), insercao do
-- proprio usuario, e NENHUMA policy de update para quem nao modera.
--
-- A ausencia de update para o autor e deliberada: sugestao editavel depois de
-- enviada e sugestao que muda de resposta quando alguem discorda dela.
drop policy if exists pavement_suggestions_select on public.pavement_suggestions;
create policy pavement_suggestions_select on public.pavement_suggestions
  for select using (true);

drop policy if exists pavement_suggestions_insert on public.pavement_suggestions;
create policy pavement_suggestions_insert on public.pavement_suggestions
  for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists pavement_suggestions_moderacao_update on public.pavement_suggestions;
create policy pavement_suggestions_moderacao_update on public.pavement_suggestions
  for update to authenticated
  using (
    public.is_admin(auth.uid())
    or public.is_master(auth.uid())
    or exists (
      select 1 from public.pavement_streets s
      where s.id = street_id
        and s.city_id is not null
        and public.is_ambassador_of(auth.uid(), s.city_id)
    )
  )
  with check (true);

-- Metas: o publico ve o que nao e rascunho — o relatorio publico so serve se
-- for publico. Gestao e de quem responde pela cidade.
drop policy if exists community_goals_select on public.community_goals;
create policy community_goals_select on public.community_goals
  for select using (
    status <> 'rascunho'
    or public.is_admin(auth.uid())
    or public.is_master(auth.uid())
    or public.is_ambassador_of(auth.uid(), city_id)
  );

drop policy if exists community_goals_gestor_write on public.community_goals;
create policy community_goals_gestor_write on public.community_goals
  for all to authenticated
  using (
    public.is_admin(auth.uid())
    or public.is_master(auth.uid())
    or public.is_ambassador_of(auth.uid(), city_id)
  )
  with check (
    public.is_admin(auth.uid())
    or public.is_master(auth.uid())
    or public.is_ambassador_of(auth.uid(), city_id)
  );

-- Mutiroes: mesma logica. Rascunho e do organizador e de quem modera; publicado
-- e convite, e convite e publico.
drop policy if exists mutiroes_select on public.mutiroes;
create policy mutiroes_select on public.mutiroes
  for select using (
    status in ('publicado', 'encerrado')
    or organizador_id = auth.uid()
    or public.is_admin(auth.uid())
    or public.is_master(auth.uid())
    or public.is_ambassador_of(auth.uid(), city_id)
  );

drop policy if exists mutiroes_gestor_write on public.mutiroes;
create policy mutiroes_gestor_write on public.mutiroes
  for all to authenticated
  using (
    organizador_id = auth.uid()
    or public.is_admin(auth.uid())
    or public.is_master(auth.uid())
    or public.is_ambassador_of(auth.uid(), city_id)
  )
  with check (
    organizador_id = auth.uid()
    or public.is_admin(auth.uid())
    or public.is_master(auth.uid())
    or public.is_ambassador_of(auth.uid(), city_id)
  );

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 5 — GRANTS
-- ═══════════════════════════════════════════════════════════════════════════

grant select, insert on public.pavement_suggestions to authenticated;
grant select on public.pavement_suggestions to anon;
grant update on public.pavement_suggestions to authenticated;

grant select, insert, update on public.community_goals to authenticated;
grant select on public.community_goals to anon;

grant select, insert, update on public.mutiroes to authenticated;
grant select on public.mutiroes to anon;

grant usage, select on sequence public.pavement_suggestions_id_seq to authenticated;
grant usage, select on sequence public.community_goals_id_seq to authenticated;
grant usage, select on sequence public.mutiroes_id_seq to authenticated;

notify pgrst, 'reload schema';
