-- 215_exploracao_avancada.sql
--
-- Fase 5 do roadmap revisado (secao 36.14).
--
-- DOIS PORTOES, E ELES SAO DIFERENTES
--
-- A fase inteira "so abre com capacidade operacional e evidencia de demanda"
-- (36.14). Alem disso, o sensoriamento passivo tem um portao proprio e mais
-- duro: a ANPD recomenda o RIPD antes de iniciar tratamento de alto risco
-- (36.17), e tratamento de localizacao em segundo plano e um.
--
-- Por isso `SENSORIAMENTO_LIBERADO` e falso em src/lib/sensoriamento.js e as
-- tabelas daqui nascem vazias. A migracao cria a ESTRUTURA e as regras; ligar e
-- decisao de quem responde juridicamente pelo produto.
--
-- O QUE ESTE ARQUIVO NAO CRIA
--
-- Nao ha tabela de trajetoria, de leitura continua de sensor, de audio, nem
-- qualquer coisa que reconstrua o deslocamento de alguem. `sensing_candidates`
-- guarda pontos SOLTOS, com coordenada arredondada, e apaga sozinha o que
-- envelhece. Se uma coluna nova aqui permitir ligar dois pontos do mesmo dia em
-- ordem, ela esta indo na direcao errada.
--
-- COLECAO NAO E TERRITORIO
--
-- Territorio individual esta fora do roadmap (36.14) e o principio 6 diz que
-- ninguem e dono de rua. Duas decisoes de esquema sustentam isso:
--
--   * `collectible_discoveries` NAO tem indice unico por ponto — dez pessoas
--     descobrem a mesma praca, e a linha de uma nao impede a da outra;
--   * a policy de leitura e SO DO DONO — nao existe consulta que responda
--     "quem descobriu primeiro", porque a pergunta nao deve ter resposta.
--
-- AS POLICIES ESTAO AQUI — mesma razao da 206 em diante.

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 1 — A COLECAO DA CIDADE
-- ═══════════════════════════════════════════════════════════════════════════

-- Marcos culturais cadastrados pela moderacao.
--
-- POR QUE UMA TABELA, SE JA HA DUAS FONTES
--
-- `pavement_streets` cobre rua com historia e `tourist_spots` cobre ponto de
-- interesse — mas nem todo marco cultural e uma coisa nem outra. O coreto, o
-- muro grafitado, a arvore que a cidade conhece pelo nome: existem, importam, e
-- nao cabem em nenhuma das duas.
--
-- O que esta tabela NAO faz e substituir as outras. A colecao le as tres.
create table if not exists public.city_collectibles (
  id          bigint generated by default as identity primary key,
  city_id     bigint not null references public.cities(id) on delete cascade,

  nome        text not null,
  descricao   text,
  imagem_url  text,

  location    extensions.geometry(point, 4326) not null,

  criado_por  uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now(),

  constraint city_collectibles_nome_nao_vazio check (length(btrim(nome)) > 0)
);

comment on table public.city_collectibles is
  'Marcos culturais da cidade para a colecao. Complementa pavement_streets (rua com historia) e tourist_spots — nao os substitui.';

create index if not exists city_collectibles_por_cidade_idx
  on public.city_collectibles (city_id);

-- Ponto turistico ganha coordenada.
--
-- Ate aqui `tourist_spots` so tinha endereco, e endereco nao verifica presenca:
-- a colecao precisa saber se a pessoa esta no lugar. A coluna e NULA por
-- padrao, e a colecao ignora quem nao tem — melhor um catalogo que cresce que um
-- backfill por geocodificacao, que erraria em silencio e mandaria gente ao
-- lugar errado.
alter table public.tourist_spots
  add column if not exists location extensions.geometry(point, 4326);

comment on column public.tourist_spots.location is
  'Coordenada do ponto. Nula ate alguem marcar no mapa; a colecao so inclui pontos com coordenada, porque endereco nao verifica presenca.';

-- As visitas.
--
-- SEM UNIQUE POR PONTO, DE PROPOSITO. O unique e por (pessoa, ponto): a mesma
-- pessoa nao registra duas vezes, e pessoas diferentes registram a vontade.
create table if not exists public.collectible_discoveries (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references public.profiles(id) on delete cascade,

  -- Texto porque as fontes tem chaves de tipos diferentes (uuid em
  -- pavement_streets, bigint nas outras). Uma FK aqui exigiria tres colunas
  -- nulaveis e um CHECK de exclusividade para ganhar integridade sobre tabelas
  -- que ninguem apaga.
  ponto_id      text not null,
  tipo          text not null,

  descoberto_em timestamptz not null default now(),

  constraint collectible_discoveries_tipo_valido check (
    tipo in ('rua_historica', 'ponto_turistico', 'marco_cultural')
  )
);

comment on table public.collectible_discoveries is
  'Visitas registradas. Leitura SO DO DONO: nao existe consulta que responda "quem descobriu primeiro" — a pergunta transformaria o ponto em algo de alguem (principio 6).';

create unique index if not exists collectible_discoveries_uma_por_pessoa
  on public.collectible_discoveries (user_id, ponto_id);

-- O catalogo, unindo as tres fontes.
--
-- Rua entra so quando tem historia escrita: uma rua sem `honoree_name` e sem
-- biografia nao e checkpoint cultural, e incluir todas transformaria a colecao
-- numa lista de logradouros.
create or replace function public.colecao_da_cidade(p_city_id bigint)
returns table (
  id     text,
  tipo   text,
  nome   text,
  resumo text,
  lat    double precision,
  lng    double precision
)
language sql
stable
security definer
set search_path = public, extensions
as $fn$
  select
    s.id::text,
    'rua_historica',
    s.name,
    coalesce(nullif(btrim(s.honoree_name), ''), 'Rua com história registrada'),
    extensions.st_y(s.location::extensions.geometry),
    extensions.st_x(s.location::extensions.geometry)
  from public.pavement_streets s
  where s.city_id = p_city_id
    and s.location is not null
    and (
      length(btrim(coalesce(s.honoree_name, ''))) > 0
      or length(btrim(coalesce(s.biography, ''))) > 0
    )

  union all

  select
    t.id::text,
    'ponto_turistico',
    t.name,
    t.short_description,
    extensions.st_y(t.location::extensions.geometry),
    extensions.st_x(t.location::extensions.geometry)
  from public.tourist_spots t
  where t.city_id = p_city_id
    and t.location is not null

  union all

  select
    c.id::text,
    'marco_cultural',
    c.nome,
    c.descricao,
    extensions.st_y(c.location::extensions.geometry),
    extensions.st_x(c.location::extensions.geometry)
  from public.city_collectibles c
  where c.city_id = p_city_id;
$fn$;

comment on function public.colecao_da_cidade(bigint) is
  'Catalogo da colecao: ruas com historia, pontos turisticos com coordenada e marcos culturais. Nenhuma fonte foi cadastrada para a colecao — todas existem por outro motivo.';

grant execute on function public.colecao_da_cidade(bigint) to authenticated;
grant execute on function public.colecao_da_cidade(bigint) to anon;

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 2 — SENSORIAMENTO PASSIVO
-- ═══════════════════════════════════════════════════════════════════════════

-- O consentimento, com versao.
--
-- POR QUE `versao_termos`
--
-- Consentimento e para um tratamento especifico, descrito num texto. Se o texto
-- mudar — passar a coletar mais, ou por mais tempo — o consentimento anterior
-- nao vale para o novo. Sem a versao, uma alteracao de escopo herdaria em
-- silencio o "sim" que a pessoa deu para outra coisa.
--
-- POR QUE `revogado_em` EM VEZ DE APAGAR A LINHA
--
-- Apagar deixaria o sistema sem como provar que houve consentimento no periodo
-- em que houve coleta — que e justamente o que a LGPD pede que se demonstre. A
-- revogacao e um fato com data, nao um sumico.
create table if not exists public.sensing_consent (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references public.profiles(id) on delete cascade,

  versao_termos text not null,
  aceito_em     timestamptz not null default now(),
  revogado_em   timestamptz,

  created_at    timestamptz not null default now()
);

comment on table public.sensing_consent is
  'Consentimento para sensoriamento passivo, por versao de termo. Revogar grava data — nao apaga a linha: e preciso poder demonstrar que houve consentimento no periodo em que houve coleta.';

create index if not exists sensing_consent_ativo_idx
  on public.sensing_consent (user_id, aceito_em desc)
  where revogado_em is null;

-- Os candidatos.
--
-- COORDENADA ARREDONDADA, E O BANCO COBRA ISSO
--
-- O cliente arredonda (`arredondar`, 4 casas ≈ 11 m). O CHECK aqui garante que
-- uma versao futura do app — ou uma requisicao montada a mao — nao grave
-- coordenada cheia. Precisao e o tipo de coisa que volta sozinha numa
-- refatoracao de "melhorar a deteccao".
--
-- NAO HA COLUNA DE PATRULHA, DE VELOCIDADE NEM DE SEQUENCIA
--
-- Cada uma delas ajudaria a agrupar pontos, e agrupar pontos e reconstruir
-- trajeto. O candidato e solto por desenho.
create table if not exists public.sensing_candidates (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references public.profiles(id) on delete cascade,

  lat           double precision not null,
  lng           double precision not null,
  intensidade   integer,

  ocorreu_em    timestamptz not null,

  resposta      text,
  confirmado_em timestamptz,

  created_at    timestamptz not null default now(),

  constraint sensing_candidates_resposta_valida check (
    resposta is null or resposta in ('buraco', 'outro_problema', 'lombada', 'nada', 'nao_lembro')
  ),
  constraint sensing_candidates_resposta_tem_data check (
    (resposta is null) = (confirmado_em is null)
  ),
  -- Espelha CASAS_DECIMAIS em src/lib/sensoriamento.js.
  constraint sensing_candidates_coordenada_grosseira check (
    lat = round(lat::numeric, 4)::double precision
    and lng = round(lng::numeric, 4)::double precision
  )
);

comment on table public.sensing_candidates is
  'Solavancos detectados durante patrulha, com consentimento. Privados do autor, expiram em 7 dias e NUNCA viram bronca sozinhos — a confirmacao posterior e da pessoa.';
comment on column public.sensing_candidates.lat is
  'Arredondada a 4 casas (~11 m) pelo cliente, e o CHECK cobra. Precisao maior seria mais dado do que o necessario (principio 9).';

create index if not exists sensing_candidates_pendentes_idx
  on public.sensing_candidates (user_id, ocorreu_em desc)
  where confirmado_em is null;

-- A retencao, sem cron.
--
-- Este projeto nao tem agendador, e criar um para apagar linhas seria
-- infraestrutura nova para uma tarefa que cabe no proprio caminho de escrita:
-- ao inserir um candidato, os vencidos DAQUELE usuario somem. O trabalho e
-- limitado (as linhas de uma pessoa) e acontece exatamente quando ha atividade.
--
-- A policy de leitura tambem filtra por data, entao um usuario que parou de
-- usar o app nao ve candidato velho mesmo antes de a limpeza rodar. As duas
-- juntas: invisivel na hora, apagado no proximo uso.
create or replace function public.limpar_candidatos_vencidos()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $fn$
begin
  delete from public.sensing_candidates
  where user_id = new.user_id
    and confirmado_em is null
    and ocorreu_em < now() - interval '7 days';
  return new;
end;
$fn$;

drop trigger if exists z_sensing_candidates_retencao on public.sensing_candidates;
create trigger z_sensing_candidates_retencao
after insert on public.sensing_candidates
for each row execute function public.limpar_candidatos_vencidos();

-- Revogar apaga o que ainda nao foi confirmado.
--
-- E a promessa do termo ("ao desligar, os pontos ainda nao confirmados sao
-- apagados") escrita como gatilho, para nao depender de a tela lembrar.
create or replace function public.apagar_candidatos_ao_revogar()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $fn$
begin
  if new.revogado_em is not null and old.revogado_em is null then
    delete from public.sensing_candidates
    where user_id = new.user_id
      and confirmado_em is null;
  end if;
  return new;
end;
$fn$;

drop trigger if exists z_sensing_consent_revogacao on public.sensing_consent;
create trigger z_sensing_consent_revogacao
after update of revogado_em on public.sensing_consent
for each row execute function public.apagar_candidatos_ao_revogar();

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 3 — IA ASSISTIVA AVALIADA POR CATEGORIA
-- ═══════════════════════════════════════════════════════════════════════════
--
-- O registro do que foi sugerido e do que a pessoa escolheu. E o unico dado que
-- torna "avaliada por categoria" possivel — e ele so existe porque a sugestao
-- NAO decide: houve uma escolha para comparar.
--
-- POR QUE NAO HA TABELA DE PLACAR AGREGADO
--
-- Mesma escolha da 169, 198 e 213: o agregado e derivado. Uma coluna
-- `acertos` precisaria de trigger e ficaria errada no dia em que alguem
-- corrigisse uma linha — e o numero errado aqui liberaria uma sugestao ruim para
-- a cidade inteira.

create table if not exists public.assist_suggestions (
  id            bigint generated by default as identity primary key,
  user_id       uuid references public.profiles(id) on delete set null,

  categoria_id  text not null,
  escolhida_id  text,
  aceita        boolean not null,

  created_at    timestamptz not null default now()
);

comment on table public.assist_suggestions is
  'Cada sugestao de categoria e o que a pessoa escolheu depois. Alimenta a avaliacao POR CATEGORIA — a entrega literal da fase 5.';

create index if not exists assist_suggestions_por_categoria_idx
  on public.assist_suggestions (categoria_id, created_at desc);

-- A avaliacao, derivada.
--
-- Janela de 180 dias: um assistente melhora e piora, e a media de sempre
-- esconderia tanto a melhora quanto a piora. O que interessa e como ele esta
-- indo agora.
create or replace function public.assist_avaliacao()
returns table (
  categoria_id text,
  sugeridas    integer,
  aceitas      integer
)
language sql
stable
security definer
set search_path = public, extensions
as $fn$
  select
    s.categoria_id,
    count(*)::integer,
    count(*) filter (where s.aceita)::integer
  from public.assist_suggestions s
  where s.created_at >= now() - interval '180 days'
  group by s.categoria_id;
$fn$;

comment on function public.assist_avaliacao() is
  'Acerto por categoria nos ultimos 180 dias. Espelha o que habilitadaPara() consome em src/lib/iaAssistiva.js. Derivada: nao ha coluna de placar para divergir.';

grant execute on function public.assist_avaliacao() to authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 4 — RLS
-- ═══════════════════════════════════════════════════════════════════════════

alter table public.city_collectibles        enable row level security;
alter table public.collectible_discoveries  enable row level security;
alter table public.sensing_consent          enable row level security;
alter table public.sensing_candidates       enable row level security;
alter table public.assist_suggestions       enable row level security;

-- Marcos: catalogo publico, escrita de quem responde pela cidade.
drop policy if exists city_collectibles_select on public.city_collectibles;
create policy city_collectibles_select on public.city_collectibles
  for select using (true);

drop policy if exists city_collectibles_gestor_write on public.city_collectibles;
create policy city_collectibles_gestor_write on public.city_collectibles
  for all to authenticated
  using (
    public.is_admin(auth.uid())
    or public.is_master(auth.uid())
    or public.is_ambassador_of(auth.uid(), city_id)
  )
  with check (
    public.is_admin(auth.uid())
    or public.is_master(auth.uid())
    or public.is_ambassador_of(auth.uid(), city_id)
  );

-- Visitas: SO O DONO, em tudo.
--
-- Nem admin le. Nao e desconfianca da moderacao: e que nao existe pergunta
-- legitima da moderacao sobre onde uma pessoa passeou — e uma tabela que
-- responde essa pergunta acaba respondendo-a.
drop policy if exists collectible_discoveries_own on public.collectible_discoveries;
create policy collectible_discoveries_own on public.collectible_discoveries
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- Consentimento: so o dono ve e escreve o proprio.
drop policy if exists sensing_consent_own on public.sensing_consent;
create policy sensing_consent_own on public.sensing_consent
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- Candidatos: so o dono, e so os que ainda estao na janela.
--
-- O filtro de data na PROPRIA policy e a segunda metade da retencao: mesmo que
-- a limpeza nao tenha rodado, o que venceu ja nao existe para ninguem.
drop policy if exists sensing_candidates_own on public.sensing_candidates;
create policy sensing_candidates_own on public.sensing_candidates
  for all to authenticated
  using (
    user_id = auth.uid()
    and ocorreu_em >= now() - interval '7 days'
  )
  with check (user_id = auth.uid());

-- Sugestoes: cada um grava a propria; ninguem le linha a linha.
--
-- A avaliacao sai de `assist_avaliacao`, que e SECURITY DEFINER e devolve so
-- totais. Abrir a leitura linha a linha diria quais categorias uma pessoa
-- especifica costuma registrar — que e perfil de comportamento, e nao e
-- necessario para nada aqui.
drop policy if exists assist_suggestions_insert_own on public.assist_suggestions;
create policy assist_suggestions_insert_own on public.assist_suggestions
  for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists assist_suggestions_admin_select on public.assist_suggestions;
create policy assist_suggestions_admin_select on public.assist_suggestions
  for select to authenticated
  using (public.is_admin(auth.uid()) or public.is_master(auth.uid()));

-- ═══════════════════════════════════════════════════════════════════════════
-- PARTE 5 — GRANTS
-- ═══════════════════════════════════════════════════════════════════════════

grant select on public.city_collectibles to anon;
grant select, insert, update, delete on public.city_collectibles to authenticated;
grant select, insert, delete on public.collectible_discoveries to authenticated;
grant select, insert, update on public.sensing_consent to authenticated;
grant select, insert, update, delete on public.sensing_candidates to authenticated;
grant select, insert on public.assist_suggestions to authenticated;

grant usage, select on sequence public.city_collectibles_id_seq to authenticated;
grant usage, select on sequence public.collectible_discoveries_id_seq to authenticated;
grant usage, select on sequence public.sensing_consent_id_seq to authenticated;
grant usage, select on sequence public.sensing_candidates_id_seq to authenticated;
grant usage, select on sequence public.assist_suggestions_id_seq to authenticated;

notify pgrst, 'reload schema';
